### ISSUE TITLE
Support anchor links for pageview tracking

### ISSUE THREAD

**Issue by eikaramba** [MatteoGabriele/vue-gtag#103]
In the old  GA library when i just had the basic setup with
```
  Vue.use(
    VueGtag,
    {
      config: { id: "UA-XXXXX" }
    },
    router
  );
```
(of course the syntax looked a little bit different with the old library)

when i clicked a link `/#test` it was tracked as a pageview. **In the new library it is not tracked anymore.**

Can you enable that or tell me what needs to be done to support this?

Sample Code from the app is:
`<v-btn to="/#test">test</v-btn>`

**Comment by biapar** [comment]
I've the same problem.

**Comment by MatteoGabriele** [comment]
yeah the issue is that path is always `/` in your case, because the hash is added to another property called `hash`.
in the other library I used a option to skip same paths, so maybe that would work in this case.
I will add it either way because it could be useful in other scenarios as well

**Comment by MatteoGabriele** [comment]
you can add `pageTrackerSkipSamePath: false` to the plugin options and should work.
let me know if works for you

**Comment by eikaramba** [comment]
great! yes it works. thank you
