### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by P4sca1** [MatteoGabriele/vue-gtag#104]
Getting the following error: https://sentry.io/share/issue/55b5039da9784a738c0fd71bc244a2e6/
It only occured on FireFox until now.

**Comment by MatteoGabriele** [comment]
is it an SSR application?

**Comment by P4sca1** [comment]
Yes

**Comment by P4sca1** [comment]
I came around with this problem, by calling `$gtag` functions within a try / catch block, so that they do not interrupt auth flows on error:
```ts
try {
  this.$gtag.event('login'
} catch (err) {
  this.$sentry.captureException(err)
}
```
I'm not sure, but I thought gtag might error when using browsers / extensions that block it.

**Comment by MatteoGabriele** [comment]
if you still have this error please let me know and create a reproduction for me to check. for now I will close it

**Comment by TitanFighter** [comment]
I had this issue when `foundItems` was undefined.

```
Vue.$gtag.event('add_to_cart', {
    const foundItems = myArray.find(myObj => myObj.itemName === someName)
    items: [foundItems]
})
```
