### ISSUE TITLE
Best practices implementation

### ISSUE THREAD

**Issue by codeofsumit** [MatteoGabriele/vue-gtag#147]
Hi Matteo, have you seen this article?

https://philipwalton.com/articles/the-google-analytics-setup-i-use-on-every-site-i-build/

It’s fantastic and I’m currently thinking about doing a raw implementation of gtag/analytics to follow these examples. 
But maybe they are also great to extend your module 🤔. 
What’s your take on that?

Thanks for your work!

**Comment by MatteoGabriele** [comment]
Unfortunately this is just for analytics. the article is quite old too and gtag is quite new. Gtag is a different library and would be nice if they tell people how to get the best out of it

**Comment by MatteoGabriele** [comment]
But thanks a lot for sharing, definitely nice to read and maybe could get something out of it

**Comment by codeofsumit** [comment]
woah you're right. I haven't even seen that it's 3 years old already 🤦  - sorry about that!
