### ISSUE TITLE
IP anonymization

### ISSUE THREAD

**Issue by Nenino2** [MatteoGabriele/vue-gtag#150]
Due to EU law, IP anonymization is required.

How can you set IP anonymization on vue-gtag library?

https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization

**Comment by yonego-delano** [comment]
With the removal of all config params the past 3 releases, we also need a solution to pass our additional config. I can't find any solutions within the documentation, perhaps this is an oversight?

Besides `anonymize_ip` we also like to pass `send_page_view`, `custom_map` for setting custom dimensions and `optimize_id` to name a few.

Would love to hear what I should do to restore this with the latest `vue-gtag` release?

**Comment by yonego-delano** [comment]
@MatteoGabriele Awesome, thanks for the quick support! I will patiently wait for a solution, and fix our version to 1.6.2 in the meanwhile.

**Comment by dneeleman** [comment]
FYI: Removed the other Github account. I'm the Ghost above 😜

**Comment by dneeleman** [comment]
Hi! Just checking in wondering what the status of this bug is. Thanks again!
