### ISSUE TITLE
Handle router base path

### ISSUE THREAD

**Issue by DanFaudemer** [MatteoGabriele/vue-gtag#160]
Hello,

Thank you for your library :). It seems that it does not handle the `base` path from the vue router for page views: 

```
var router = new Router({
  base: process.env.NODE_ENV === 'production'
    ? '/app/'
    : '/',
```
This happens when the public path is not `/`.

Is it the expected behavior as it can be managed by custom template?

**Comment by MatteoGabriele** [comment]
I will look into it, thanks for your feedback :)

**Comment by PureLines** [comment]
I've the same issue.

@MatteoGabriele did you have a chance to take a look?

**Comment by DanFaudemer** [comment]
@PureLines below my solution using custom template:

```
Vue.use(VueGtag, {
  config: { id: 'UA-*******' },
  pageTrackerTemplate: function (to, from) {
    return {
      page_title: to.name,
      page_path: process.env.NODE_ENV === 'production' ? '/app' + to.path : to.path,
      page_location: window.location.href
    }
  }
}, router)
```

**Comment by PureLines** [comment]
> ```
> Vue.use(VueGtag, {
>   config: { id: 'UA-*******' },
>   pageTrackerTemplate: function (to, from) {
>     return {
>       page_title: to.name,
>       page_path: process.env.NODE_ENV === 'production' ? '/app' + to.path : to.path,
>       page_location: window.location.href
>     }
>   }
> }, router)
> ```

Yes, it works, thanks @DanFaudemer.

And I improved with:
```
    page_path: router.options.base + to.path,
```

**Comment by MatteoGabriele** [comment]
@PureLines @DanFaudemer sorry for the enormous delay. has been a busy year :D 
let me know if works as expected
