### ISSUE TITLE
Main config parameters are applied to all Multiple domain tracking entries

### ISSUE THREAD

**Issue by dneeleman** [MatteoGabriele/vue-gtag#165]
### Description

When configuring Multiple domain tracking, all parameters given to the main config are applied to the other `includes` as well. Even with overriding the params in the config for the other domain(s).

### Expected behavior

I believe the params should only be applied to the given domains.

### Actual behavior

When configuring Multiple domain tracking, all parameters given to the main config are applied to the other `includes` as well. Even with overriding the params in the config for the other domain(s).

### Environment

**vue-gtag@1.8.0** 

1. Operating system: Mac OSX 10.15.6
2. Browser and version: Chrome 84.0.4147.89

### Reproducible Demo

We have a "rollup" Google Analytics Account, this will receive all events from all our websites. Therefor we initialize the rollup account with the [Multiple Domain Tracking configuration](https://matteo-gabriele.gitbook.io/vue-gtag/multiple-domain-tracking), just like we did on **Vue-GTAG version 1.6.2**. Except the result now is that the default params for `rollupId` is ignored and is populated with the params from the main config.

```
const defaultParams = {
    anonymize_ip: true,
    send_page_view: false,
    custom_map: {}
}

export const getDefaultParams = () => defaultParams

const config = {
    config: {
        id: conceptId,
        params: {
            ...getDefaultParams(),
            ...{
                optimize_id: optimizeId,
                custom_map: customMap
            }
        }
    },
    includes: [{
        id: rollupId,
        params: getDefaultParams()
    }]
}

// Internally use the vue-gtag module.
// https://github.com/MatteoGabriele/vue-gtag
Vue.use(VueGtag, config)
```

**Comment by dneeleman** [comment]
@MatteoGabriele any updates regarding if this is desired behavior? I assume this might fly under the radar for most people.

**Comment by dneeleman** [comment]
@MatteoGabriele any updates regarding if this is desired behavior? I assume this might fly under the radar for most people.

**Comment by MatteoGabriele** [comment]
I will have a look in the following weeks probably, still pretty busy right now, unfortunately.

Thanks for your feedback.

I'm also working on the redesign for Vue 3 as well so I will try to squeeze this in

**Comment by dneeleman** [comment]
@MatteoGabriele I really appreciate it, thank you.
