### ISSUE TITLE
[Feature Request] custom gtag.js url

### ISSUE THREAD

**Issue by manniL** [MatteoGabriele/vue-gtag#167]
Hey all 👋🏻

The predecessor plugin, `vue-analytics` had the feature to provide a [custom analytics URL](https://matteogabriele.gitbooks.io/vue-analytics/docs/custom-analytics.html). With `vue-gtag`, this doesn't seem possible at the moment.

Would you accept a PR implementing such a feature?

**Comment by MatteoGabriele** [comment]
Sure thing :)
