### ISSUE TITLE
New to Analytics does <script> provided by google is add it explicitly

### ISSUE THREAD

**Issue by prashantnirgun** [MatteoGabriele/vue-gtag#176]
Its not a bug just a information required as I am new to Google Analytics. Google Analytics provide a <script> to be added into header file. Which I believe is not required if we are using vue-gtag.

May I didn't find this in question section so I asked it. I tried adding the library but google Analytics is not showing site hit counts.

**Comment by MatteoGabriele** [comment]
you don't have to add anything, you only need to pass your domain ID and the plugin takes care of the rest

```js
// example
Vue.use(VueGtag, {
  config: { id: "UA-1234567-1" }
});
```

if you also want to track page switch automatically, you can pass the router instance as third parameter


```js
// example
const router = new VueRouter({ ... })

Vue.use(VueGtag, {
  config: { id: "UA-1234567-1" }
}, router);
```

for other things you can look at the documentation

- [vue-gtag documentation](https://matteo-gabriele.gitbook.io/vue-gtag/)
- [gtag.js official documentation](https://developers.google.com/analytics/devguides/collection/gtagjs)
