### ISSUE TITLE
pageTrackerScreenviewEnabled missing config id

### ISSUE THREAD

**Issue by acgotakuatdji** [MatteoGabriele/vue-gtag#178]
### Description

If we enable `pageTrackerScreenviewEnabled`, vue-gtag missing below command:

```
gtag('config', 'GA_MEASUREMENT_ID');
```

 

`pageTrackerScreenviewEnabled: false`

![GTScreenshot_20200828_141614](https://user-images.githubusercontent.com/38874985/91524516-6465f580-e93a-11ea-9594-19217ad1f4fb.png)

`pageTrackerScreenviewEnabled: true`

![GTScreenshot_20200828_141657](https://user-images.githubusercontent.com/38874985/91524520-65972280-e93a-11ea-8c26-c123543e6f11.png)

 
### Reproducible Demo

Demo repo: https://github.com/acgotakuatdji/test-vue-gtag

**Comment by MatteoGabriele** [comment]
thanks @acgotakuatdji 
I'll have a look and let you know asap

**Comment by MatteoGabriele** [comment]
@acgotakuatdji I had to do quite some changes actually but should all work out now. please let me know if it's fixed.

thanks a lot

**Comment by acgotakuatdji** [comment]
@MatteoGabriele  Yes, fixed! Thank you very much!
