### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by saibbyweb** [MatteoGabriele/vue-gtag#190]
### Description
My Vue app become inaccessible if I pass the **router** object as the third argument

```
Vue.use(VueGtag, {
  config: { id: "UA-1234567-1" }
}, router);
```

### Expected behavior

It should let users add vue router, so that GA doesn't only track the default '/' path for every page view.

### Actual behavior
But instead it throws this error
```
Maximum call stack size exceeded
    at Function.assign (<anonymous>)
```

### Environment

Running `npm ls vue-gtag` returns **`-- vue-gtag@1.9.0**

OS: Windows 10
Browser: Google Chrome: Version 85.0.4183.83

### Reproducible Demo

I googled this issue and it turns out it may be a caused due to circular reference within vue components. My Vue app is ready and it consists of 100's of components, it is impossible to find out the circular reference (if there's any) without checking each and every component one by one. For a quick fix, I am setting the page view manually with

```
this.$gtag.pageview({ page_path: this.$route.path });
```

in **mounted()** method of _App.vue_

### Suggestion
As most people will use this package at the end of any vue project. It would be really helpful , if you can somehow manage to help us spot the file/vue-component/route causing this issue. Otherwise, it would be total nightmare for big projects.

Thanks for reading.

**Comment by MatteoGabriele** [comment]
hi @saibbyweb thanks for filling the template, unfortunately tho you need to create a representation of your issue in a separate repo and link it to me or see if you can make it on code sandbox or something like it.
needs to be the simplest setup possible so that I can easily identify the cause of this.
this because the issue could be caused by something very specific in your own project and I wouldn't know where to start.

thanks a lot

**Comment by MatteoGabriele** [comment]
I will close this issue due to inactivities, but please feel free to re-open it once there is a reproduction of the issue available.

**Comment by snickbit** [comment]
I'm having the same issue, here's a reproduction: https://codesandbox.io/s/gtag-error-fcdtk

**Comment by MatteoGabriele** [comment]
@snickbit judging by the example u made, you have to pass the router as a third argument in the `use` method, not as a property of the second argument.
I get that is confusing and that's why in the next version of vue-gtag for vue 3, this has changed to make it easier to implement

**Comment by joweste** [comment]
I have the same problem. Here is my main.js:

```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import vuetify from "./plugins/vuetify";

import VueMeta from "vue-meta";
Vue.use(VueMeta);

import VueGtag from "vue-gtag";

Vue.use(VueGtag, {
  config: {
    id: "G-P5YQT6PD5D",
    params: {
      send_page_view: false,
    },
  },
  router,
});

//dialogs
import VuetifyDialog from "vuetify-dialog";
import "vuetify-dialog/dist/vuetify-dialog.css";

Vue.use(VuetifyDialog, {
  context: {
    vuetify,
  },
});

//validaçao de forms
import Vuelidate from "vuelidate";
Vue.use(Vuelidate);

Vue.config.productionTip = false;

Vue.mixin({
  methods: {
    getDeepErrors: function (outerObj, outerKey) {
      let self = this;
      const obj = outerObj[outerKey];
      return Object.keys(obj).reduce((acc, key) => {
        if (key.charAt(0) === "$" && key !== "$store" && key !== "$each")
          return acc;
        if (typeof obj[key] === "object") {
          return acc.concat(self.getDeepErrors(obj, key));
        }
        if (!obj[key]) {
          acc.push({
            key: outerKey,
            error: key,
            params: obj.$params[key],
          });
        }
        return acc;
      }, []);
    },
  },
});

new Vue({
  router,
  store,
  vuetify,
  render: (h) => h(App),
}).$mount("#app");

```

**Comment by MatteoGabriele** [comment]
@joweste you have to read tho. The comment right before yours is the correct install.

**Comment by joweste** [comment]
> @joweste you have to read tho. The comment right before yours is the correct install.

Thanks. It was solved
