### ISSUE TITLE
Correct way to add a second property (Adwords) to config

### ISSUE THREAD

**Issue by Sharpoon** [MatteoGabriele/vue-gtag#196]
The docs for gtag.js show how to add a second property to the global site tag by setting a new config `gtag('config', 'GA_MEASUREMENT_ID_2');` . How is this achieved with vue-gtag. Is it ok to just add a global site tag for Adwords alongside the vue-gtag setup which is using a Google Analytics Id.

Thanks

Steve

**Comment by MatteoGabriele** [comment]
you currently have to do it like this https://matteo-gabriele.gitbook.io/vue-gtag/multiple-domain-tracking
this will change and me more easy to customise with the next version
