### ISSUE TITLE
Failing to load GA property Id from .env variables

### ISSUE THREAD

**Issue by vitomargiotta** [MatteoGabriele/vue-gtag#198]
Hi, first of all thanks a million for this simply outstanding and useful project! 

When directly hardcoding the Google Analytics domain ID in the config file it all works like a charm. However when retrieving them from env variables, it no longer works. Any idea why and how to fix it?

_Vue.use(
  VueGtag,
  {
    config: { id: process.env.VUE_APP_GOOGLE_ANALYTICS_PROPERTY_ID },
  },
  router
);_

note: of course I confirm that env variable is properly set, as i can access it anywhere else in the app.

Thanks a lot and I wish you a great day!
Vito

**Comment by MatteoGabriele** [comment]
Hey thanks a lot for your feedback. Really appreciate it.
It's kinda weird to be honest, it should just work. Just out of curiosity, in the same file, can you console log that variable correctly?
Otherwise I would need a reproduction repo to see this happening

**Comment by vitomargiotta** [comment]
yes @MatteoGabriele i am able to console.log the env variable with no issue.

update: while building a repo for you to test with I realized I actually mispelled the env variable (I and l are way too similar..)...

I am very sorry for taking your time, and I confirm it actually all works as expected!

**Comment by MatteoGabriele** [comment]
No worries man, that's why making a reproduction outside our projects it's always a good idea cause often we don't make the same mistakes or at least we have less code to look at

Cheers
