### ISSUE TITLE
Enable / Disable Function

### ISSUE THREAD

**Issue by fabianwohlfart** [MatteoGabriele/vue-gtag#199]
Is there a way to enable() and disable() the plugin after enable: false in the config?
I cannot find it in the documentation.

**Comment by MatteoGabriele** [comment]
yes, there is and I don't know why I didn't add it to the documentation. sorry about that.
you can use the `this.$gtag.optIn()` or `this.$gtag.optOut()`

those are all the methods you can access from the `$gtag` object in your component context
```
  query,
  config,
  event,
  pageview,
  screenview,
  customMap,
  time,
  exception,
  linker,
  purchase,
  refund,
  set,
  optIn,
  optOut,
```

**Comment by Liam26** [comment]
It's worth noting this was closed but has not been added to the gitbook documentation yet, took me a while to find this and others may still be looking.

**Comment by pulakchakraborty** [comment]
@MatteoGabriele Could you please update the info in the gitbook documentation? I was stuck on this for quite a while untill i started looking at all the issues :(

**Comment by MatteoGabriele** [comment]
oh jeez! so sorry. I added them in the `next` version, but forgot here

https://matteo-gabriele.gitbook.io/vue-gtag/api
