### ISSUE TITLE
Unable to track User Id 

### ISSUE THREAD

**Issue by aakritsubedi** [MatteoGabriele/vue-gtag#200]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description
 - Unable to track user id data or not clearly mentioned in document

What are you reporting?
- user id analytics 

### Expected behavior
- set user id in analytics 

Tell us what you think should happen.

### Actual behavior

Tell us what actually happens.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-gtag`: 

Then, specify:

1. Operating system: Ubuntu 
2. Browser and version: Chrome latest 

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by MatteoGabriele** [comment]
I see that you have properly filled up the template....
![image](https://media4.giphy.com/media/TJawtKM6OCKkvwCIqX/giphy.gif)

**Comment by MatteoGabriele** [comment]
btw if you want to add it at start you can do 

```js
Vue.use(gtag, {
  config: {
    id: 'UA-12345678-8',
    params: {
      user_id: 'foo'  
    }
  }
})
```

if you need to set it in specific place your might want to do this in your component

```js
this.$gtag.config({ user_id: 'foo' })
```

it really depends on your needs

**Comment by aakritsubedi** [comment]
Thank you
