### ISSUE TITLE
FEATURE REQUEST: option to load the script with `defer` attribute.

### ISSUE THREAD

**Issue by hsblhsn** [MatteoGabriele/vue-gtag#201]
I don't want the gtag.js to load on my site like this:

```
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-159330658-2&amp;l=dataLayer" charset="utf-8"></script>
```

I want it like this

```
<script defer src="https://www.googletagmanager.com/gtag/js?id=UA-159330658-2&amp;l=dataLayer" charset="utf-8"></script>
```

Here is how it impacts the site.

![](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_13.png)

Please provide an option for this.

**Comment by MatteoGabriele** [comment]
I've added the `deferScriptLoad` boolean option in the list of plugin options

**Comment by TitanFighter** [comment]
@MatteoGabriele docs do not have this option -> https://matteo-gabriele.gitbook.io/vue-gtag/plugin-options

**Comment by MatteoGabriele** [comment]
Didn't have time, sorry. I will update it

**Comment by goodwillsandy** [comment]
@MatteoGabriele Is there any way using which we can add this defer attribute also for additional 'gtag script' whose id is added in `includes`?
