### ISSUE TITLE
Possible to add multiple IDs to config?

### ISSUE THREAD

**Issue by srchulo** [MatteoGabriele/vue-gtag#211]
Is there a way to add multiple IDs (analytics, adwords) to the config? I can only find the example of one:

```
Vue.use(VueGtag, {
  config: { id: "UA-1234567-1" }
});
```

If this is possible, it would be great to have an example in the documentation.

Or would I need to do something after that to add another ID, like:

`this.$gtag.config('adwords_id')`

**Comment by MatteoGabriele** [comment]
Is this what you are looking for? https://matteo-gabriele.gitbook.io/vue-gtag/multiple-domain-tracking

**Comment by srchulo** [comment]
I think that did it, thank you! Sorry I missed that in the documentation.

I wonder if it might be good to put that example in the getting started section? It wasn't clear to me that "Multiple Domain Tracking" would mean this, but maybe I'm just not familiar enough with Google's lingo!

Thanks!

**Comment by srchulo** [comment]
Actually, I included that, and although I see it making the request for gtag.js, I don't see page views or conversion events being sent to the other "domain", just to the UA id.

**Comment by MatteoGabriele** [comment]
can u make a reproduction of this error?

**Comment by MatteoGabriele** [comment]
I will close this issue due to inactivities, but please feel free to re-open it once there is a reproduction of the issue available.
