### ISSUE TITLE
Inject config ID dynamically

### ISSUE THREAD

**Issue by mittalyashu** [MatteoGabriele/vue-gtag#215]
I am trying to inject config ID dynamically after querying it from database.

First I have initialised the vue-gtag in `main.js`

```js
Vue.use(VueGtag);
```

And in `app.vue` inside created lifecycle hook.

```js
created() {
  // db query for google analytic ID

  this.$gtag.config({
    id: 'UA-12345678-0' // dynamic ID
  });
}
```

This didn't work out.

**Comment by MatteoGabriele** [comment]
No that's the config command from gtag. 
I am working on the vue3 version and it has a lot of these fixes and u can customize the whole process easier. Not sure if i can bring the same changes on this current version.
I will try to make some time. 

Right now you can go to the documentation and use the alternative bootstrap logics.

https://matteo-gabriele.gitbook.io/vue-gtag/custom-installation#set-options

I think there's a typo in the example and you should be able to install the plugin without adding any config objects in the install options.

I'm not in front of my computer right now so can't double check. Let me know if it works

Thanks

**Comment by mittalyashu** [comment]
On looking into the documentation and implementing `setOptions` it did work.

Do you have any thoughts on performance cost for initialisation `vue-gtag` before mounting Vue app or inside a component?

**Comment by MatteoGabriele** [comment]
no i don't think there are any drawbacks. it's a matter of preferences and availability of your data: like if you have or not the domain ID statically

**Comment by mittalyashu** [comment]
Quick question, does that mean we can't inject dynamic config ID before vue.js getting initialised?

I can create a PR on that topics to make it more clear for other devs.

**Comment by MatteoGabriele** [comment]
Well you to be able to download the gtag snippet you need an ID to attach to the URL. To achieve this with an ID coming from the database you would do the bootstrap as we said before. Other than that, whatever u can do with gtag, u can do here. Its the same library

**Comment by mittalyashu** [comment]
Thanks for the help.

I am closing this issue.
