### ISSUE TITLE
Chrome plugin Google Tag Assistant registering multiple tags

### ISSUE THREAD

**Issue by TobiasGOhmy** [MatteoGabriele/vue-gtag#216]
Hello!
I noticed that my site is adding multiple gtag-scripts when I check my website with the "Google Tag Assistant" chrome plugin. Is this intended? It keeps adding more and more scripts when I change routes (according to the plugin). I can see it registers page views in GA, but i'm afraid the numbers wont be accurate because of this.

My implementation looks like this:

Vue.use(VueGtag, {
  config: {
    id: GTAG_ID
  }
}, router);

![image](https://user-images.githubusercontent.com/44799434/96410040-941cd580-11e6-11eb-8e2c-f0b255c93b15.png)

**Comment by hhanckes** [comment]
Same here. Any advice? Thanks.

**Comment by MatteoGabriele** [comment]
What do you mean for "gtag-scripts"?

**Comment by hhanckes** [comment]
If you use the "tag assistant" that's a chrome addon you'll see the following warning message: "Multiple installations of Global site tag (gtag.js) detected". Attached the screenshot:

<img width="454" alt="Screen Shot 2020-11-05 at 1 37 32 PM" src="https://user-images.githubusercontent.com/1490884/98269115-24d80d00-1f6c-11eb-9d30-437def793ddb.png">

**Comment by luke-hawk** [comment]
+1

**Comment by MatteoGabriele** [comment]
I've been using the tag assistant but for me looks different and it doesn't really say nothing about multiple installation.
I literally run their script once, so I am not sure what to do.
Any suggestions?

<img width="1717" alt="Screenshot 2020-11-12 at 20 54 56" src="https://user-images.githubusercontent.com/5337152/98989428-6139d900-2529-11eb-932f-9fcbfc3929c7.png">

**Comment by raminjafary** [comment]
@MatteoGabriele This is a common issue of Google Tag Assistant in SPA routing. It can't detect page transitions correctly so it loads the GTM (or GTAG) container for each URL. As far as you see one request per page in your browser's Network requests, everything is working properly! I think we can add this somewhere in the docs!

**Comment by MatteoGabriele** [comment]
Thanks a lot for the update, I'm sure the ticket itself will be enough for people to look at. If i have time, i might add it to an article I'd like to write for the upcoming version 2
