### ISSUE TITLE
Enhanced Ecommerce support

### ISSUE THREAD

**Issue by Renaldekoker** [MatteoGabriele/vue-gtag#217]
Hi, 

How can I use this package to send enhanced e-commerce data like in the vue-analytics package? 

I tried doing, but GA doesn't action this as an EC event. 

$gtag.event('productClick', {ecommerce: click: {...}})

**Comment by MatteoGabriele** [comment]
on gtag.js it's called `purchase`

**Comment by MatteoGabriele** [comment]
here the official documentation link https://developers.google.com/analytics/devguides/collection/gtagjs/ecommerce
