### ISSUE TITLE
Query string parameters not appearing in google analytics

### ISSUE THREAD

**Issue by HairMachine** [MatteoGabriele/vue-gtag#229]
### Description

When visiting a page that contains query parameters, (such as /blah?foo=bar), the query parameters do not appear in the google analytics dashboard - so only /blah is appearing.

I believe this started happening when we switched from the original vue-analytics version of the library to this one; query parameters had previously been working fine.

I am not 100% sure whether this is expected behaviour and I'm missing some configuration, a bug in the library, or something strange with our implementation (although the vue site I'm seeing this occur on is very simple). Searching on google and probing the code hasn't got me anywhere so far.

### Expected behavior

When the user visits a page that has query parameters, these are tracked and appear in the Google Analytics dashboard.

### Actual behavior

The query parameters don't appear in the Google Analytics dashboard.

### Environment

vue-gtag@1.10.0 

Linux Mint 18 Sarah

Google Chrome 81.0.4044.129

**Comment by HairMachine** [comment]
Update on this one: after probing further, I found downgrading the module to 1.6.4 fixes the problem. All versions above that seem to stop passing query strings.

**Comment by daidais** [comment]
To resolve this I set pageTrackerSkipSamePath to false and give atemplate for pageTrackerTemplate like this :
```js
...
        pageTrackerSkipSamePath: false,
        pageTrackerTemplate(to) {
          return {
            page_title: to.name,
            page_path: to.fullPath,
            page_location: window.location.href,
          };
        },
...
```

But it could be great to check the fullPath for duplicate to

**Comment by MatteoGabriele** [comment]
@HairMachine sorry for the long-delayed response. I have added a new option that makes you use the `fullPath` instead of the `path` when you are dealing with automatic page tracking.

thanks for your feedback

**Comment by daidais** [comment]
Thank you! :)
