### ISSUE TITLE
How to set cookie_flags?

### ISSUE THREAD

**Issue by havardl** [MatteoGabriele/vue-gtag#230]
In Firefox I'm getting the following error in the console: 
`Some cookies are misusing the recommended “SameSite“ attribute`

I've tried to set the SameSite attribute to comply, but it doesn't seem to have an effect. This is my current implementation, am I misunderstanding how to set these variables?

```javascript    
Vue.use(VueGtag, {
      config: {
        id: "UA-XXXXXXXX-X",
        cookie_domain: "https://www.mydomain.com",
        cookie_flags: "SameSite=None;Secure",
      },
      enabled: true,
      disableScriptLoad: false,
      bootstrap: false,
      pageTrackerEnabled: true,
    });
```

**Comment by MatteoGabriele** [comment]
Yes the `config` objects has 2 properties `id` and `params`
Try to put those two paraments inside the `params` object. Should work

**Comment by havardl** [comment]
Hi @MatteoGabriele, thanks for the clarification. Can confirm that this works.
