### ISSUE TITLE
Google Analytics 4 support ?

### ISSUE THREAD

**Issue by jpichon21** [MatteoGabriele/vue-gtag#231]
Hi,

I'm currently looking to add vue-gtag in a Vue 2 project, but It seems that the Universal Analytics "UA-XXXXXX-X" tag is no longer support since Analytics 4 (October 2020).

Should I wait for a vue-gtag update ?

Thank you

**Comment by lassesteffen** [comment]
This library also works with the new tag without a problem

**Comment by MatteoGabriele** [comment]
gtag.js already supports GA4
