### ISSUE TITLE
bootstrap() causes Uncaught TypeError: b is undefined

### ISSUE THREAD

**Issue by pbujko** [MatteoGabriele/vue-gtag#232]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

`Uncaught TypeError: b is undefined  seen at the bootsrap` seen in browser console and no events stopped to be reported to google

### Actual behavior
Issue started appearing all of a sudden since Nov 5th

### Environment
-    "vue": "^2.6.11",
-    "vue-gtag": "^1.8.0" 

1. Operating system:
2. Browser and version:
Firefox running on both MacOS and Windows

### Reproducible Demo

```    enableGtag() {
      console.log("enabling gtag");
      bootstrap().then((gtag) => {
        this.$store.dispatch("setGtagBootstraped", Date.now());
      });
    },
```

exception is reported from inside of `bootstrap()`

**Comment by AliasIO** [comment]
I'm having the exact same issue. The error is coming from GA, perhaps the API changed. I switched to [@nuxtjs/google-gtag](https://www.npmjs.com/package/@nuxtjs/google-gtag) as I'm using Nuxt anyway, no issue there.

**Comment by cheindel** [comment]
I have the same problem. Did you find a solution for this?

**Comment by MatteoGabriele** [comment]
can't reproduce this. I'm going to close the ticket, but if you can create a repo with the issue I will have a look immediately,
thanks for your feedback and sorry for the huge delay on texting you back
