### ISSUE TITLE
Sending events to multiple tracking ids does not work

### ISSUE THREAD

**Issue by a-r-t** [MatteoGabriele/vue-gtag#233]
### Description

Sending events to multiple tracking ids does not work using the example from the docs: https://matteo-gabriele.gitbook.io/vue-gtag/multiple-domain-tracking

### Expected behavior

After installing the plugin like this:
```js
Vue.use(VueGtag, {
   config: {
        id: 'some-google-analytics-tracking-id'
    }
    includes: [
        { id: 'some google-adwords-tracking-id' }
    ]
}
```

I should be able to run the below command to send an event to a particular tracking id using the "send_to" param:
```js
this.$gtag.event('conversion', {
    send_to: 'some google-adwords-tracking-id',
    value: 0
})
```

### Actual behavior

The "send_to" param is ignored and the event will only be sent to the initial tracking id (in this case  'some-google-analytics-tracking-id'). Excluding the "send_to" param will still only have it be sent to the initial tracking id as well.

### Environment

vue-gtag@1.9.1

MacOS Mojave version 10.14.5
Google Chrome version 75

### Reproducible Demo

Code provided in above sections

**Comment by MatteoGabriele** [comment]
I'm sorry but I can't reproduce this issue. I am able to send events with multiple domains listed in the send_to and if I want to override the send_to for a particular event, I can just simply pass it.

**Comment by MatteoGabriele** [comment]
```js
Vue.use(VueGtag, {
  config: {
    id: 'UA-1234567-1',
  },
  includes: [{
    id: 'UA-1234567-2'
  }]
})
```
with 

```js
export default {
  name: 'MyComponent',

  methods: {
    track() {
      console.log('clicked', this.$gtag)
      this.$gtag.event('clicking', {
        event_category: 'ux',
        event_label: 'user clicked something',
        value: 1,
      })
    }
  }
}
```

this will produce 

```js
gtag('event', 'clicking', {
  event_category: 'ux',
  event_label: 'user clicked something',
  value: 1,
  send_to: ['UA-1234567-2', 'default']
})
```

if then I use this snippet 

```js
export default {
  name: 'MyComponent',

  methods: {
    track() {
      console.log('clicked', this.$gtag)
      this.$gtag.event('clicking', {
        event_category: 'ux',
        event_label: 'user clicked something',
        value: 1,
        send_to: ['I will send it somewhere else']
      })
    }
  }
}
```

I will send this 

```js
gtag('event', 'clicking', {
  event_category: 'ux',
  event_label: 'user clicked something',
  value: 1,
  send_to: ['I will send it somewhere else']
})
```

please provide better reproduction of this issue and reopen the ticket.
thanks a lot for your feedback
