### ISSUE TITLE
Still no data reporting in Google Analytics

### ISSUE THREAD

**Issue by didiosn** [MatteoGabriele/vue-gtag#241]
Hello, it's been 3 days, that i've add bue-gtag to my project but I still do not have data on my dashboard. 
My snippet : 
`Vue.use(
        VueAnalytics,
        {
            id: 'G-KVGJ7X4JBG'
        },
        router);`

How can I fix it ? 

Thanks

**Comment by MatteoGabriele** [comment]
I'm a bit confused by the variable name but i assume you are using vue-gtag and not vue -analytics.

The property is `config.id`, not just `id`

You should check the documentation

**Comment by didiosn** [comment]
Hi don't worry about the variable name, I was using VueAnalytics : 

`import VueAnalytics from 'vue-gtag';`

Ok, let me change like this : 

`Vue.use(VueAnalytics, { config.id: 'G-KVGJ7X4JBG' }, router);`

**Comment by MatteoGabriele** [comment]
Well not literally, what I mean is that it's an object called config with a
property called id.

Please just follow the documentation

**Comment by didiosn** [comment]
Hi, Thank you for your, I'm getting data now. Thanks.
