### ISSUE TITLE
Possible bug with vue-gtag (Reported by sentry)

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [MatteoGabriele/vue-gtag#243]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

Sentry issue: https://sentry.io/share/issue/c153585cc6c94f9f9ca96d3728dab9cf/

### Description

An error keeps coming up saying that cant ready the property groups of undefined.

### Expected behavior

This error should be handled by skipping action or trying again and should not return a TypeError.

### Actual behavior

Crashes the library.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-gtag`:  vue-gtag@1.9.0

Then, specify:

1. Operating system: Can check at sentry 
2. Browser and version: Can check at sentry

**Comment by MatteoGabriele** [comment]
I know I'm very late on this one but the sentry link is expired, do you still have this issue?

thanks for your feedback and sorry for the huge delay 🙏

**Comment by MatteoGabriele** [comment]
I will close this issue due to inactivities, but please feel free to re-open it once there is a reproduction of the issue available.
