### ISSUE TITLE
First hit is not sent if bootstrap with delay

### ISSUE THREAD

**Issue by soylomass** [MatteoGabriele/vue-gtag#248]
If I bootstrap the plugin with a delay, when the executions reaches this code:

```
Router.onReady(function (current) {
    Vue.nextTick().then(function () {
      api.config(config.params);
      trackPage({
        to: current
      });
    });
```

The current param is undefined.

I solved the problem changing:
to: current

To:
to: Router.currentRoute

**Comment by MatteoGabriele** [comment]
@soylomass thanks a lot for your feedback and sorry for the huge delay in responding and fixing this. 🙏
