### ISSUE TITLE
Nuxt track page views

### ISSUE THREAD

**Issue by dclawson** [MatteoGabriele/vue-gtag#249]
I am looking for a way to track page views automatically using Nuxt and vue-gtag.

I am unable to use the VueRouter as suggested in the docs as Nuxt does not expose this.

I have tried using custom middleware but can't seem to access `$gtag` this way.

Is there a preferred way to track all page views using Nuxt or expose the `$gtag` to context somehow?

**Comment by timmygee** [comment]
Hey @dclawson I had the same problem. You can actually access nuxt router from the context in your plugin and pass it to vue-gtag like so:

```JS
import Vue from 'vue'
import VueGtag from 'vue-gtag'

export default ({ app }) => {
  Vue.use(
    VueGtag,
    {
      config: { id: ... },
    },
    app.router
  )
}
```

Hope that helps!

**Comment by MikesGlitch** [comment]
If anyone's looking for an example there's one here: https://github.com/MikesGlitch/mikesglitch.com/tree/main/googleanalytics

It may need some modifications for your specific scenario

**Comment by jsagon** [comment]
Hi @dclawson, I'm using your solution, but I'm struggling to figure out how can I work with dynamic pages(routes). 
Example /articles/_slug.

The vue-gtag is sending the payload as
```
{
dl: https://mysite.com/articles/my-article-title,
dt: articles-slug,
ep.page_path: /articles/my-article-title
}
```
My Google Analytics (page view) is counting the **dt** field (multiples views for articles-slug ) and not the dl (the article title). 
Do you know how can I fix this?

Reference
![image](https://user-images.githubusercontent.com/11699360/183223231-aa951e40-3686-4e81-ae26-05d14a503535.png)

**Comment by MikesGlitch** [comment]
@jsagon If you're using Nuxt I've got an example of a working config for you:

https://github.com/MikesGlitch/mikesglitch.com/blob/main/src/plugins/googleAnalyticsPlugin.client.ts

The thing to remember is it takes the HTML title tag as the "page title" in the report - so it has to be called something better than "pub-articles-slug" on that page.  

![image](https://user-images.githubusercontent.com/5285928/183258959-7fc0c883-7eec-4c3b-8d6a-a963783412cd.png)
