### ISSUE TITLE
IP Anonymization

### ISSUE THREAD

**Issue by diogoaguiar** [MatteoGabriele/vue-gtag#250]
Is it possible to enable IP Anonymization, as in the [gtag.js documentation](https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization)?

I tried passing it on the global config but I'm not sure it's doing anything.

**Comment by MatteoGabriele** [comment]
I'm sorry but "I'm not sure" is not enough for me.
I tried it and it works like any other argument.
if you have an issue, create a repository that proves it and I will take a look

**Comment by WolfgangDrescher** [comment]
Am I correct that the right way to use it is the following?

```js
Vue.use(VueGtag, {
  config: { 
    id: "UA-1234567-1",
    params: {
      anonymize_ip: true,
    },
  },
});
```

**Comment by MatteoGabriele** [comment]
@WolfgangDrescher correct
