### ISSUE TITLE
How get clientId

### ISSUE THREAD

**Issue by vitomargiotta** [MatteoGabriele/vue-gtag#251]
### Description

In order to use the measurement protocol I am required to pass the clientid. However I am struggling with understanding how to get it using vue-gtag. Any clue? Or is it not possible to achieve currently? 
Thank you so much for this repo and I wish you a great day

### Actual behavior

I tried following the guide here: https://developers.google.com/gtagjs/reference/api#get
as follow:
Vue.$gtag('get', process.env.VUE_APP_MEASUREMENT_ID, 'client_id', (clientid) => {
  console.log(clientid)
})
but it errors "Uncaught (in promise) TypeError: vue__WEBPACK_IMPORTED_MODULE_8__.default.$gtag is not a function"

**Comment by MatteoGabriele** [comment]
I didn't add the `get` api method, but as stated in the documentation, whatever is missing, you can simply use the `query` method which gives you full access to the gtag library

sorry for the ridiculous late response

**Comment by rubencanovaca** [comment]
ok, so `this.$gtag.query('get', ...)`

and what should I put in the `...` part?

**Comment by imanshafiei540** [comment]
@rubencanovaca I'm using something like this:
`vue-gtag`: `1.16.1`
```
 this.$gtag.query("get", "G-XXXXXX", "client_id", (clientID) => {
        console.log(clientID);
})
```
