### ISSUE TITLE
Using methods within components should check for enabled or not?

### ISSUE THREAD

**Issue by erlendoverby** [MatteoGabriele/vue-gtag#259]
I have implemented some consent support, storing the consent value in the localStore.
In my main.js I'm checking for the value of the localStore consent value, and based on that I either initiate a new consent dialog (localStore value === null) using the bootstrapping methods when consent is given, when localStore value is true I'll load the scripts and initiate VueGtag as expected, when consent is not given, I'll set the VueGtag enabled to false, and bootstrap/disablescriptLoad to true. And it works almost expected - no loading of google stuff when consent is not given, and no loading of google files before consent is given.

However; when I use this.$gtag methods in my different components for reporting different usage, I get the following errors when GTAG have enabled: false:

```````
TypeError: can't access property "apply", window[globalObjectName] is undefined
    query vue-gtag.esm.js:140
    event vue-gtag.esm.js:176
    screenview vue-gtag.esm.js:230
```````

I invoke the following command from within different components:

``````javascript
 this.$gtag.screenview({
        app_name: 'foo',
        screen_name: 'bar',
      })
``````

I think it would be nice if the vue-gtag library checked the "enabled" value before any report methods was invoked?
It would be more "natural" if the enabled check was managed within the vue-gtag library :-)

Anyway - the tools work as expected and are a huge pleasure to work with. Keep up the great work.

Cheers
Erlend Øverby

**Comment by MatteoGabriele** [comment]
could you create a reproduction of this issue in a very simple Vue app? thanks a lot and sorry for the huge delay in coming back to you 🙏

**Comment by jepster-dk** [comment]
Just chiming in here to say that I'm experiencing the same issues as Erlend. 
I'm using it in a Nuxt app, which is giving me some headaches. 

The nuxt-google-analytics and nuxt-facebook-pixel-module libraries handle this quite gracefully, for comparison. 

(And I agree with Erlend: `Anyway - the tools work as expected and are a huge pleasure to work with. Keep up the great work.`)
