### ISSUE TITLE
Docs site does not load

### ISSUE THREAD

**Issue by rnicholus** [MatteoGabriele/vue-gtag#26]
On https://matteo-gabriele.gitbook.io/vue-gtag/ -

> Error: could not handle the request

**Comment by MatteoGabriele** [comment]
Are you sure? Works for me even on a private window

**Comment by MatteoGabriele** [comment]
Also I don't really host the docs, it's gitbook.io. maybe a momentaneous problem or some connectivity issues. I'll close it.

Thanks anyway
