### ISSUE TITLE
Hidding warn message in production

### ISSUE THREAD

**Issue by Azurox** [MatteoGabriele/vue-gtag#261]
Hi,
Users using Brave or AdBlock will receive this message in the console : 
`[vue-gtag] Ops! Something happened and gtag.js couldn't be loaded`

I don't think that it's possible to hide any warning message coming from vue-gtag, 
Maybe adding a handler in the plugin option to be able to catch those errors and not throw them in the console would be better ? Not sure about this :) 

Thank you for your library !

**Comment by roxburghm** [comment]
I second this.

When using an error reporting library this gets reported as a JS error when it is in fact just a routine event.

Either provide an option to supress the error or change the console.error to a console.log or console.warning

**Comment by MatteoGabriele** [comment]
I went for the console.warn options
