### ISSUE TITLE
pageview not showing up in google analytics

### ISSUE THREAD

**Issue by ktmellow** [MatteoGabriele/vue-gtag#263]
Can someone help show me what I'm missing? I'm able to see users' initial page views but not when using pageview methods in my components. Even though the page views are missing, I see the network calls to google analytics when the components mount.

In app file:
```javascript
Vue.use(VueGtag, {
  config: { id: 'G-##########' },
})
```

In component:
```javascript
export default {
  name: 'MyComponent',

  methods: {
    track () {
      this.$gtag.pageview({
        page_path: '/mypage',
      })
    }
  },
  mounted() {
    this.track()
  }
}
```

**Comment by TitanFighter** [comment]
Duplicate -> https://github.com/MatteoGabriele/vue-gtag/issues/262
