### ISSUE TITLE
Proxying vue-gtag using Nginx to bypass Adblock and other blockers

### ISSUE THREAD

**Issue by xaander1** [MatteoGabriele/vue-gtag#264]
Is it possible to change the analytics domain where vue-gtag points to in order to bypass adblock and other blockers. 
Here is a guide of what I mean : [using nginx to bypass blockers](https://gist.github.com/paivaric/211ca15afd48c5686226f5f747539e8b)
So instead of: `https://www.google-analytics.com/analytics.js` to point to `/analytics.js` 

Or how does vue-gtag address blockers??

**Comment by camero2734** [comment]
Got this working by using the `customResourceURL`. In this case, I mapped it to `/gtag`:

```js
// This is @nuxtjs/proxy
"/gtag": {
      target: "https://www.googletagmanager.com",
      pathRewrite: {
        "/gtag": "/gtag/js"
      },
      secure: true
}

// vue-gtag config
Vue.use(
    VueGtag,
    {
      config: { id: ctx.env.gaId },
      customResourceURL: "/gtag"
    },
    ctx.app.router
);
```

**Comment by xaander1** [comment]
How are you automatically getting the route in ​`ctx​.​app​.​router​`
