### ISSUE TITLE
In Nuxt this.$gtag is undefined in actions of vuex store

### ISSUE THREAD

**Issue by julianfox** [MatteoGabriele/vue-gtag#273]
### Description

In Nuxt this.$gtag is undefined in actions of vuex store

### Expected behavior

Be able to access gtag in actions of vuex store

### Actual behavior

$gtag is undefined, work well in components

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-gtag`:  vue-gtag@1.11.0

Then, specify:

1. Operating system: Mac Os 10.14
2. Browser and version: Google chrome: Version 88.0.4324.182 (Official Build) (x86_64)

### Reproducible Demo

```
async signupWithLocal ({ dispatch, rootState }, payload) {
    const { $auth, $axios, $gtag } = this

    ...

    await $auth.setUserToken(data.token)

    try {
      this.$gtag.set({
        'userId': $auth.user._id
      })
    } catch (e) {
      console.log(e)
    }
}
```

**Comment by pierresaid** [comment]
Use vm in nuxt

```typescript
this._vm.$gtag
```

**Comment by MatteoGabriele** [comment]
vue-gtag is not available in the vuex context, you should import it like this

```js
import { set } from 'vue-gtag'

set({ userId: 'foo' })
```

check all methods here https://matteo-gabriele.gitbook.io/vue-gtag/api

**Comment by Coinhexa** [comment]
> Use vm in nuxt
> 
> ```ts
> this._vm.$gtag
> ```

undefined inside a nuxt 2 plugin
