### ISSUE TITLE
Realtime tracking went on after optOut()

### ISSUE THREAD

**Issue by georgenis** [MatteoGabriele/vue-gtag#279]
### Description

I am reporting a bug. I have a cookie consent, which disables the gtag with "this.$gtag.optOut()". In my google analytics dashboard i can see realtime data and how i interact with my webapp. How can I disable the whole tracking?

### Expected behavior

I think it should show any realtime data anymore, after i disabled it with optOut().

### Environment

`npm ls vue-gtag`:  vue-gtag@1.11.0
1. Operating system: MacOSX (current)
2. Browser and version: Chromium 89.0.4389.90 (arm64)

### Reproducible Demo

`this.$gtag.optOut()`

**Comment by MatteoGabriele** [comment]
Opt-out uses the built-in feature of the library which still fires events but never sends them: they are all aborted.

**Comment by georgenis** [comment]
Why is it visible in my Google Analytics dashboard? It isnt GDPR compliant, is it?

**Comment by MatteoGabriele** [comment]
the method is part of google API and opts you out from tracking: will still "fire" events, but they are aborted so it's probably not 100% GDPR compliant because you are still downloading the script. You are not storing any data though.

**Comment by MatteoGabriele** [comment]
if you want a "bullet proof" GDPR solution, you should bootstrap the plugin only if the user accepts your conditions
