### ISSUE TITLE
Incorrect page title reported via Analytics

### ISSUE THREAD

**Issue by popovicidinu** [MatteoGabriele/vue-gtag#282]
### Description

Hi! I'm working on a project with NuxtJS (SSR mode) and I've installed this library to use with GA v4. It pretty much works outside the box, but I've noticed that if you use "pageTrackerScreenviewEnabled", the dt value is not properly reported on subsequent navigations.  

Example: 

Page 1: (rendered from SSR): correctly reports the values on the screenview event
Page 2: (navigating to a link - I think this is rendered browser based): the screenview event "dt" property still has the old value
Page 3: (navigating to another link): the screenview event "dt" property has the value from page 2

I checked the code and it seems to be correct, by using the router.onReady and router.afterEach events, but somehow, even if Vue.nextTick is used, it doesn't actually ensure the entire DOM was loaded.  

### Expected behavior

The library should report the correct page title to analytics. 

### Actual behavior

The library reports the previous page title to analytics on subsequent navigations in the browser. 

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-gtag`: vue-gtag@1.11.0

Then, specify:

1. Operating system: Mac OS
2. Browser and version: Chrome

### Reproducible Demo

`
export default ({ app }) => {
    Vue.use(VueGtag, {
      config: { id: 'G-XXXXX' },
      appName: 'XXXX',
      pageTrackerScreenviewEnabled: true
    }, app.router)
}
`
<img width="404" alt="Screenshot 2021-04-08 at 18 16 49" src="https://user-images.githubusercontent.com/12153294/114052685-ec2fbd00-9896-11eb-82ed-017621d4b13a.png">
<img width="363" alt="Screenshot 2021-04-08 at 18 17 08" src="https://user-images.githubusercontent.com/12153294/114052691-ed60ea00-9896-11eb-86ff-61aa4c596203.png">
<img width="431" alt="Screenshot 2021-04-08 at 18 20 00" src="https://user-images.githubusercontent.com/12153294/114052859-16817a80-9897-11eb-94dc-4e570b668f6e.png">

The third image show the title from the second image. The second image from the first image. And the first image is correct, because the page was rendered via SSR.

**Comment by MatteoGabriele** [comment]
unfortunately, SSR always gives issues with vue-router, I can't do much more than waiting for VueRouter to be ready and triggering a nextTick on each route change.
This is more an issue with Nuxt or VueRouter or both combined.
