### ISSUE TITLE
Is vue-gtag currently not supporting GA-4?

### ISSUE THREAD

**Issue by akhilesh-k** [MatteoGabriele/vue-gtag#287]
Hi everyone, I tried integrating vue-gtag for the new GA-4 property on Google analytics. I tried GA-4 default property, GA-4 Property with GA Universal Analytics and Universal Analytics only.

It turned out that vue-gtag is sending data only for the last case which is, Universal Analytics only. Has anyone tried implementing the GA-4 property or it is not supported at all by vue-gtag? Please clarify.

**Comment by MatteoGabriele** [comment]
@akhilesh-k as far as I know, code-wise, there is no additional code that I need to add to make GA4 properties usable.
the plugin so far is exposing main API methods like pageviews, events, config, etc.. but for everything else that you don't find and you want to access, you can use the `query` method and write `query('add_shipping_info', ...)`, for example.
The `query` method simply uses the library as it is: it would be like calling `gtag('add_shipping_info', ...)`

I hope I made things more clear.

if instead you think that the plugin is missing something to be able to use these functionalities, please let me know

**Comment by MatteoGabriele** [comment]
I will close this issue due to inactivities, but please feel free to re-open it once there is a reproduction of the issue available.

**Comment by robertoshimizu** [comment]
Matteo, in order ro use vue-gtag with GA-4, could you please confirm the new syntax of the id, supposedly former UA-XXXXXXXX-X. The thing is that GA-4 does not supply a tracking ID anymore, but rather a property id, which I have tried to intuitively add to the config, but it did not work out.

**Comment by MatteoGabriele** [comment]
I should probably change all the UA-123456789 IDs in the doc with GA_MEASUREMENT_ID just like gtag doc writes. This is the same API of gtag.js, whatever ID google wants, that's what you need to put

**Comment by robertoshimizu** [comment]
You are quite right Matteo, in fact I used the new form G-XXXXXXXXXX in the same field and it worked just fine. Thank you for your prompt response.

**Comment by aleksandr-kn** [comment]
> You are quite right Matteo, in fact I used the new form G-XXXXXXXXXX in the same field and it worked just fine. Thank you for your prompt response.

Hi, did you simply replace id old ga-3 id in config (UA-XXXXXXXX-X) with web stream id (G-XXXXXXXXXX) from google analytics 4, and it worked? Because for some reason when i do that, all the events are still sent to ga3 property. And by the way i'm using version 1 of the library with vue2

**Comment by ons-attia** [comment]
Hey @aleksandr-kn were you able to make it work?

**Comment by Torone** [comment]
It doesn't work. version 1 doesn't support GA4.

**Comment by soyaine** [comment]
> It doesn't work. version 1 doesn't support GA4.

@Torone do you use version 1 too? is there any way to make it work in version1 & vue2.0

**Comment by Torone** [comment]
@soyaine, I tried to use v.1 because my project is based on Nuxt 2 and Vue 2.0, but it doesn't work. It looks like no one is updating plugins to allow GA4 to Nuxt 2 and Vue 2.0, and the only solution is to create a custom js file to include the script. Unless someone will update the plugins to allow GA4...
