### ISSUE TITLE
unable to associate and verify ownership of analytics property to the Google Search Console property

### ISSUE THREAD

**Issue by lohithn4** [MatteoGabriele/vue-gtag#290]
### Description
I am able to add vue-gtag with nuxt and it is working, able to view real-time analytics.
Now I am trying to link Analytics property to the Search Console property. but it is failed with an error "Ownership verification"

### Expected behavior

Since vue-gtag has been added to my website and google-analytics is working, associating google search console property also must work.
### Actual behavior

error "Ownership verification failed"
Failed reason: the google analytics tracking code on your site looks malformed.

### Environment
vue-gtag@1.14.0

1. Operating system: Ubuntu 18.04
2. Browser and version: Chrome Version 90.0.4430.85 (Official Build) (64-bit).

![Screenshot from 2021-04-25 11-23-50](https://user-images.githubusercontent.com/18326676/115983012-67de7900-a5bc-11eb-8a44-2bbe76f95de4.png)
![Screenshot from 2021-04-25 11-39-23](https://user-images.githubusercontent.com/18326676/115983023-73ca3b00-a5bc-11eb-89ef-5d9235e8b9d6.png)

**Comment by MatteoGabriele** [comment]
Looks like something specific to your project. I'm not familiar with what u have to do, but I'm pretty sure is not due to the plugin but to some of your account configurations.
Maybe to get rid of the doubts, try to create a small app using a custom gtag implementation and try to achieve the same results. If it doesn't fail, I'll look into it

**Comment by MatteoGabriele** [comment]
Could you post here your plugin installation snippet?

**Comment by lohithn4** [comment]
This is my vue-gtag.js plugin.
```
import Vue from 'vue'
import VueGtag from 'vue-gtag'

export default ({ app }) => {
  Vue.use(
    VueGtag,
    {
      config: app.$config.googleAnalytics,
    },
    app.router
  )
}

```
nuxt.config.js
```
plugins:[...,
    { src: '~/plugins/vue-gtag' },
],
```

Anyway there are many methods by which we can authorise our ownership, i tried including HTML Meta tag in head option it worked out very well for me.

```
  head: {
     ....
    meta: [
      { charset: 'utf-8' },
      {
        name: 'google-site-verification',
        content: 'encrypted_codexyz',
      },
     ...
    ],
  },
```

But i could not figure out why google-analytics code option failed....
Since it is resolved for me, i am closing it off.
Thanks for the response.
