### ISSUE TITLE
[BUG] send_page_view false but initial pageview still being sent

### ISSUE THREAD

**Issue by danieltamas** [MatteoGabriele/vue-gtag#291]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

The config option **send_page_view** set to false is not working as expected

### Expected behavior

The initial pageview should be disabled

### Actual behavior

The **pageview** event is being triggered 

### Environment
nuxt@2.15.4
vue-gtag@1.14.0

Then, specify:

1. MacOS
2. Chrome: version 90.0.4430.85 (Official Build) (x86_64)

### Reproducible Demo

```
import Vue from 'vue';
import VueGtag from 'vue-gtag';
import ENV from '@/nuxt_configs/env';

export default ({ app, store, router }, inject) => {
    
    Vue.use(VueGtag, {
        disableScriptLoad: process.client && navigator.webdriver ? true : false,
        bootstrap: process.client && navigator.webdriver ? false : true,
        pageTrackerEnabled: false,
        pageTrackerScreenviewEnabled: false,
        pageTrackerSkipSamePath: false,
        config: {
            id: ENV.default.PUBLISHER.GTRACKING_ID,
            params: {
                debug_mode: ENV.DEV,
                send_page_view: false
            },
        }
    });

    inject('gtag', Vue.$gtag);
}

**Comment by MatteoGabriele** [comment]
the send_page_view false it's only for the first config hit so that we skip double-tracking of the first page, but then you do need to track your first page: it's the landing hit.

**Comment by MatteoGabriele** [comment]
I will close this issue due to inactivities
