### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by MatteoGabriele** [MatteoGabriele/vue-gtag#3]
how to enable debugging in gtag?

**Comment by MatteoGabriele** [comment]
I've downloaded the "GTM Debug" extension from Chrome.

**Comment by razbakov** [comment]
You can also add [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) to documentation about debug. It activateds verbose console output and exceptions from gtag.

**Comment by MatteoGabriele** [comment]
no, that's for google analytics which will download analytics_debug.js, but gtag.js doesn't have it apparently

**Comment by razbakov** [comment]
Well it shows debug information in console about gtag triggering. I haven't look deep what exactly it does but it's helpful.

Also there is a [Google Tag Assistant](https://support.google.com/tagassistant/answer/2947093) extension.
