### ISSUE TITLE
how to use this if I want to send data to both UA3 and GA4?

### ISSUE THREAD

**Issue by vesper8** [MatteoGabriele/vue-gtag#310]
I've been using vue-gtag for a month on a new project where I selected to create a new GA4 property, but I am not happy with the interface and features of GA4 so I am now reverting to UA3

It's my understanding that vue-gtag supports both UA3 and GA4 properties.

When creating a UA3 property on Google (by clicking on 'advanced settings' while creating a new property) there is an option to create both a GA4 and UA3 property

From doing some research about that, it looks like those who want to send data to both systems essentially have to add two sets of javascript tags to their site, one with the UA-XXX code and one with the new G-XXX code

<img width="1166" alt="Screen Shot 2021-05-04 at 7 50 56 PM" src="https://user-images.githubusercontent.com/816028/117083464-6e53ba00-ad4d-11eb-97e0-c43bb968c9fd.png">

Now the question is.. if vue-gtag supports both types of codes.. if one wants to populate both UA3 and GA4 with data.. how do we do that? Do we instantiate vue-gtag twice with the two different codes or .. what ?

Many thanks!

**Comment by MatteoGabriele** [comment]
this is the part of the documentation that you talk about, I assume https://developers.google.com/analytics/devguides/collection/ga4/basic-tag?technology=gtagjs

to achieve what this page says, you just need to write this and everything should work

```js
import Vue from 'vue'
import VueGtag from 'vue-gtag'

Vue.use(VueGtag, {
  includes: [{ id: 'G-XXXXXXXXXX' }],
  config: {
    id: 'UA-XXXXXX-13'
  }
})
```

let me know if it works for you

**Comment by vesper8** [comment]
Thank you! It appears to work : )

**Comment by the94air** [comment]
It would be great if the `includes` option was documented on the docs. As the currently we can't use the GA4 using the `config.id` option and it's required to use the `includes` option instead.
