### ISSUE TITLE
load tag id asyncronous

### ISSUE THREAD

**Issue by mikimoresi** [MatteoGabriele/vue-gtag#316]
Hello,
i need to get the googletag id with an ajax call and then load the plugin, is it possible?
Thank you

**Comment by joshjung** [comment]
The documentation is confusing. The documentation seems to imply that you *must* provide the google tag id even if bootstrap is false.

**Comment by MatteoGabriele** [comment]
If you read the example after that, you will see that is possible to add it later https://matteo-gabriele.gitbook.io/vue-gtag/custom-installation#set-options

**Comment by joshjung** [comment]
Okay that was rather confusing, it looks like the first section is implying that you must have it. So I just didn't bother reading further since it was clear it was required when bootstrap is false.

**Comment by MatteoGabriele** [comment]
@joshjung Please, feel free to create an issue and suggest better documentation: this one is far from being perfect
