### ISSUE TITLE
Add Conversion tracking codes

### ISSUE THREAD

**Issue by Kalindu123** [MatteoGabriele/vue-gtag#318]
Hi 
Can we add phone conversion tracking codes using this plugin ? 
I have below code to add to my vue js app

<script> gtag('config', 'AW-1111111111/u3z7CM35hDswFcsqB-8sD', {​​​​​​​​ 'phone_conversion_number': '8765443212' }​​​​​​​​); </script> 

Thanks

**Comment by MatteoGabriele** [comment]
if that's your main configuration ID, you can simply add it statically to the plugins options
```js
Vue.use(VueGtag, {
  config: {
    id: 'AW-1111111111/u3z7CM35hDswFcsqB-8sD',
    params: {
      'phone_conversion_number': '8765443212'
    }
  }
})
```

if you don't have it statically and you are in a component context, you can use it like this

```js
this.$gtag.query('config', 'AW-1111111111/u3z7CM35hDswFcsqB-8sD', {
  'phone_conversion_number': '8765443212'
})
```
or elsewhere, you can import it directly from the package itself

```js
import { query } from 'vue-gtag'

query('config', 'AW-1111111111/u3z7CM35hDswFcsqB-8sD', {
  'phone_conversion_number': '8765443212'
})
```
