### ISSUE TITLE
Conversion tracking

### ISSUE THREAD

**Issue by Kalindu123** [MatteoGabriele/vue-gtag#328]
Hi 

I have the following code to trigger in a button click

gtag('event', 'conversion', { 'send_to': 'AW-11111111/gt9BCMWEerfgvvLqB-8sD', 'value': 99.0, 'currency': 'AUD', 'event_callback': callback }); return false; } 

How can we do this using this plugin? can we use this.$gtag.event?

Thanks

**Comment by Cosbgn** [comment]
@Kalindu123 It would look something like this:

```
this.$gtag.event('conversion', {
    'send_to': 'AW-11111111/gt9BCMWEerfgvvLqB-8sD', 
    'value': 99.0, 
    'currency': 'AUD'
})

```

**Comment by MatteoGabriele** [comment]
thanks @Cosbgn
