### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by marcbelletre** [MatteoGabriele/vue-gtag#330]
Hello there,

I would like to report a small mistake in the documentation here: https://matteo-gabriele.gitbook.io/vue-gtag/custom-installation#set-options

The second code block is wrong. The `gtag` variable should be a parameter of `then()` like this:
```js
bootstrap().then((gtag) => {
    // all done!
})
```

Thanks for this amazing plugin by the way :)

**Comment by MatteoGabriele** [comment]
Oh! Good catch. I will update that, thanks a lot
