### ISSUE TITLE
export 'nextTick' was not found in 'vue'

### ISSUE THREAD

**Issue by SumentsJavi** [MatteoGabriele/vue-gtag#332]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

What are you reporting?
Running "npm run dev" after a clean installation, it shows:
in ./node_modules/vue-gtag/dist/vue-gtag.esm.js

"export 'nextTick' was not found in 'vue'

An the app does not compile
### Expected behavior

Happily compile

### Actual behavior

it shows 
in ./node_modules/vue-gtag/dist/vue-gtag.esm.js
"export 'nextTick' was not found in 'vue'

and a blanck screen

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-gtag`: 
vue-material-dashboard-pro@1.4.0 
└── vue-gtag@2.0.1 

Then, specify:

1. Operating system:
2. Ubuntu 20
2. Browser and version:
3. Chrome Version 90.0.4430.93 (Official Build) (64-bit)

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by MatteoGabriele** [comment]
Hello @SumentsJavi can I ask you what Vue version are you running it with?

**Comment by SumentsJavi** [comment]
From "package.json", on the dependencies: "vue": "2.6.11",

**Comment by MatteoGabriele** [comment]
I thought so. Version 2.x of vue-gtag is for vue 3 only, so you need to install 1.x or use Vue 3.
I see that vue-gtag is a dependency on another package for you, so you might want to redirect your issue to them.

**Comment by akbarism** [comment]
I have the same issue, I'm using nuxt js, does this package not work in nuxt?

**Comment by MatteoGabriele** [comment]
You have to give me a bit more insights on your setup. What Vue version and what 'vue-gtag' version

**Comment by vedmant** [comment]
I have the same problem with Nuxt
