### ISSUE TITLE
Enhanced Ecommerce (Please support add_to_cart, view_item, begin_checkout...)

### ISSUE THREAD

**Issue by workingxx92** [MatteoGabriele/vue-gtag#347]
Hi. 
please support add_to_cart, view_item, begin_checkout... etc for Enhanced Ecommerce

Thank

**Comment by TitanFighter** [comment]
Everything already works

this.$gtag.event('add_to_cart', {
  currency: 'USD',
  value: 99.95,
  items: [item1, item2, etc]
})
