### ISSUE TITLE
TypeError: $gtag.event.purchase is not a function

### ISSUE THREAD

**Issue by workingxx92** [MatteoGabriele/vue-gtag#348]
TypeError: $gtag.event.purchase is not a function
    at Object.onPurchase (TrackingServices.js?ef27:70)
    at VueComponent.onSuccess (checkout.vue?4dd3:640)
    at eval (checkout.vue?4dd3:598)

**Comment by Cosbgn** [comment]
@workingxx92 should be `this.$gtag.event('purchase')`

**Comment by MatteoGabriele** [comment]
the shorthand is `this.$gtag.purchase` or you can type `this.$gtag.event('purchase')` as @Cosbgn suggested
