### ISSUE TITLE
Enable Demographics and Interests reports

### ISSUE THREAD

**Issue by kay1212** [MatteoGabriele/vue-gtag#349]
How can I Enable Demographics and Interests reports ?

I had turn on the switch  in setting "Advertising Features", and the gander or age reports in my ga are still zero. 

Pageveiw or events reports normally work well.

Should I add other codes? 

Please help me, thank you very much.

**Comment by MatteoGabriele** [comment]
I'm very sorry, but I don't know how to do that. It would be best if you consider checking the official API documentation. The plugin is a wrapper that simplifies your life with Google Analytics or Gtag, but I don't know all the tips and tricks :)

**Comment by colinxr** [comment]
Ran into this same issue today. I believe you can enable this by using the vue-gtag query method.

```
this.$gtag.query("require", "displayfeatures");
```

The query method is like using the ga object directly, as described in the docs [here](https://matteo-gabriele.gitbook.io/vue-gtag/query):
