### ISSUE TITLE
How to measuring the checkout process, with ecommerce plugin ?

### ISSUE THREAD

**Issue by owalid** [MatteoGabriele/vue-gtag#350]
Hello !
How to load the Ecommerce Plugin ?

To use like this: 

```javascript
ga('require', 'ec');

ga('ec:addProduct', {        
  'id': 'P12345',                  
  'name': 'Android Warhol T-Shirt', 
  'category': 'Apparel',            
  'brand': 'Google',                
  'variant': 'Black',               
  'position': 1,                    
  'dimension1': 'Member'  
});

ga('ec:setAction', 'click', {
  'list': 'Search Results' 
});
```

In the issue: https://github.com/MatteoGabriele/vue-gtag/issues/217 you talk about `purchase` function but purchase does not replace `ec:addProduct` or `ec:addImpression` or `ec:setAction`

thanks you 😄

**Comment by MatteoGabriele** [comment]
I'm sorry, I don't really write the API: it's just like this.
analytics and gtag are not the same things. I suggest you check the differences between these 2 libraries. The plugin basically exposes the most common gtag API methods and, if not, you can always use the `query` method to access directly gtag API
