### ISSUE TITLE
UTM Campaign Tracking

### ISSUE THREAD

**Issue by adamiss5138** [MatteoGabriele/vue-gtag#351]
How to use this plugin to track UTM campaign? As far as I know, this does not work with Vue Router. Is there any option to make it work with this plugin?

**Comment by KevinYobeth** [comment]
I encountered the same issue, how do you get around it?

**Comment by sneko** [comment]
@adamiss5138 why did you close the issue? Did you solve it?

This issue is still on going https://github.com/MatteoGabriele/vue-gtag/issues/405 so if you have any implementation to make things working properly, it would be great!

cc @KevinYobeth

**Comment by adamiss5138** [comment]
> @adamiss5138 why did you close the issue? Did you solve it?
> 
> This issue is still on going #405 so if you have any implementation to make things working properly, it would be great!
> 
> cc @KevinYobeth

I don't have the energy to even bother with this plugin anymore. Nothing worked for me as I expected. Page view tracking does not work, even if I passed the router instance to the plugin, UTM tracking does not work, and support is non-existent.

**Comment by sneko** [comment]
@adamiss5138 so at the end, did you switch to another library (if so, which one)? Or did you use the raw Google HTML/script?

**Comment by sneko** [comment]
@KevinYobeth @adamiss5138 in case you still want to solve this issue I worked on a third-party library (https://github.com/sneko/utm-synapse) that I integrated into `vue-gtag`. Please see https://github.com/MatteoGabriele/vue-gtag/pull/445 for details 👍
