### ISSUE TITLE
Error on navigating to "/" homepage route

### ISSUE THREAD

**Issue by martinthenth** [MatteoGabriele/vue-gtag#352]
Thank you for making this library. It's easy to set up and works great. I found one bug when navigating to the homepage shows errors in the console.

### Description

In production environment, when navigating from a non-home page route to the home page route `"/"`, the console displays:

`Uncaught (in promise) RangeError: Maximum call stack size exceeded`

In development environment, when navigating from a non-home page route to the home page route `"/"`, the console displays:

`[Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.`

I'm not sure what the effects are in Google Analytics, because an event seems to trigger and report to Google Analytics (but I can't be certain, because I may not be receiving all the event data because of this error).

I found two issues pertaining this problem:

[https://stackoverflow.com/questions/68100114/avoid-app-logic-that-relies-on-enumerating-keys-on-a-component-instance](https://stackoverflow.com/questions/68100114/avoid-app-logic-that-relies-on-enumerating-keys-on-a-component-instance)

[https://github.com/vuejs/vue-next/issues/2027](https://github.com/vuejs/vue-next/issues/2027)

Is VueGtag perhaps watching a whole `route` or `router` object to trigger events?

### Expected behavior

No errors when navigating to home page, 100% reporting to Google Analytics.

### Actual behavior

Errors show when navigating to home page.
This bug may prevent data being sent to Google Analytics, because the function error may crash the process.

### Environment

- `vue-gtag@2.0.1`
- `vue-router@4.0.10`
- Vue 3
- Chrome
- macOS

### Reproducible Demo

1. Create a Vue 3 app. 
2. Install latest `VueGtag`.
3. Install `VueRouter`.
4. Create two routes; one to the homepage `"/"` and another route.
5. Navigate from the second route to the homepage.
6. View console to see error.

```
createApp(App)
  .use(router)
  .use(
    VueGtag,
    {
      config: { id: 'GA-ID' }
    },
    router
  )
  .mount('#app')
```

**Comment by MatteoGabriele** [comment]
Sorry to hear that, but I do not watch any route changes; I listen to the built-in `afterEach` callback function provided by VueRouter. I've tried your simple setup with no errors anywhere.
