### ISSUE TITLE
page_title why not is document.title?

### ISSUE THREAD

**Issue by xuyanmei** [MatteoGabriele/vue-gtag#354]
I use Nuxt，vue-i18n，Because page will be used by multiple countries，web page titles are dynamic and multilingual，but it is difficult, this plugin 's page_title  use  route name，But gtag.js use the document.title,so I don't undestand the reason。route name is meaningless,I think. thank you and hope you can apply!

**Comment by h8ngtat** [comment]
vue-gtag will set the rendered page's title tag value to "page_title" if you remove app.router during plugin initialization.

**Comment by MatteoGabriele** [comment]
thanks @h8ngtat 
I assume this fixed
