### ISSUE TITLE
vue-gtag-next: Build issue

### ISSUE THREAD

**Issue by lumenier1** [MatteoGabriele/vue-gtag#355]
Unexpected behavior (bug) on `'npm run build'`.

### Expected behavior

This lib should add Google Analytics when I build my project.

### Actual behavior

There is no google tag in the html after `'npm run build'` command.
So, when I just serve my project locally, it works.
When I build project, nothing happens, no google tag is applied.

### Environment

1. Operating system: MacOS
2. Browser and version: Google Chrome latest

**Comment by MatteoGabriele** [comment]
The plugin doesn't add any tags on build time, only on runtime. You can check this by firing your app and look the HTML structure in the devtool
