### ISSUE TITLE
How can I exclude all children of a route? Also there seems to be a typo in this process in the documentation. 

### ISSUE THREAD

**Issue by sarik-k** [MatteoGabriele/vue-gtag#362]
https://matteo-gabriele.gitbook.io/vue-gtag/auto-tracking#exclude-routes

According to this, I need to pass an array of routes names or paths to the pageTrackerExcludedRotues key (Not sure if its a typo in documentation or coded like that in the package itself). I want to exclude all admin routes i.e. all routes that are the children of "admin" route.

I'm also not sure what to put if my route name is 'admin'. just 'admin' or 'route_name_admin'.

**Comment by MatteoGabriele** [comment]
Yeah, it's a typo. 
You can check the actual names here https://matteo-gabriele.gitbook.io/vue-gtag/plugin-options
I will correct the docs.

it won't check children, but literally a route name. All children have different route names, so if you need to pass Parent and Children, you have to loop them all.  You could use something like `$route.matched`
