### ISSUE TITLE
Page View auto-tracking with pageTrackerTemplate send double views

### ISSUE THREAD

**Issue by doge-dev** [MatteoGabriele/vue-gtag#372]
### Description

When configuring the lib to auto-track page views and use a custom template, the library sends the new page_title with query parameters but original page_title is sent through request payload.

<img width="756" alt="Screenshot 2021-09-04 at 15 13 22" src="https://user-images.githubusercontent.com/2998613/132095630-b926d52d-44e6-4080-b071-490e12bf3813.png">

### Expected behavior

When pageTrackerTemplate is used, only the new page_title should be sent in the page_vew request. 

### Actual behavior

The new page_title is sent through the query parameters, and the old page_title is sent through request payload.

### Reproducible Demo

Page title is the same on all pages. The initialisation of VueGtag library is done like this:

```
Vue.use(VueGtag, {
	config: {
		id: '...',
	},
	pageTrackerTemplate(to) {
		return {
			page_title: to.name,
			page_path: to.path
		};
	}
}, router);
```

**Comment by kristofferdamborg** [comment]
I had the same problem, I fixed it by unchecking "Page changes based on browser history events" in the advanced settings of "Enhanced measurement" in your data stream.

![image](https://user-images.githubusercontent.com/25890205/134906975-d739f09c-855c-42b0-9ac3-857bd10dfa78.png)

**Comment by doge-dev** [comment]
Yup that solves it, thanks @kristofferdamborg  👍
