### ISSUE TITLE
Not seeing data in Google Analytics after install

### ISSUE THREAD

**Issue by officiallymarky** [MatteoGabriele/vue-gtag#376]
### Description

Installed and configured VueGtag, but no events show up in Google Analytics

### Expected behavior

Analytics show up

### Actual behavior

Nothing reported to Google Analytics

### Environment

vue-gtag@2.0.1

Vue 3
Vite

Windows 10 (Testing)
Ubuntu 20.4 (Deploy)

Brave and others

### Reproducible Demo

```
import { createApp } from 'vue'
import store from './store'
import App from './App.vue'
import VueGtag from "vue-gtag";
import './index.css'

const app = createApp(App).use(store).use(VueGtag, {
  config: { id: "G-XXXXXXXXXX" }
}).mount('#app')
```

**Comment by bfreskura** [comment]
@officiallymarky 

Can you please describe how you solved this issue? I'm having the same problem :(

**Comment by bfreskura** [comment]
Solved it by moving GTag id environment variable from private env variables to public variables in `defineNuxtConfig` as Gtag ID should be visible on the client side in order for this plugin to work.

How the `runtimeConfig` option looks now:

```
runtimeConfig: {
    public: {
      gtagId: "",
      backendUrl: "xxxxxx",
    },
  },
```

How it looked before when it wasn't working:
```
runtimeConfig: {
    gtagId: "",
    public: {
      backendUrl: "xxxxxx",
    },
  },
```
