### ISSUE TITLE
Two tracking ids added (including one unknown)

### ISSUE THREAD

**Issue by thopit** [MatteoGabriele/vue-gtag#382]
I am using vue-gtag version 2.0.1 and added the following configuration
```
const myApp = createApp(App)
  .use(router)
  .use(VueGtag, {
    config: { id: "UA-XXXXXXXX-X" },
  })
```
After deploying the following two scripts are included in the page:
```
<script type="text/javascript" async="" src="http://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX&amp;l=dataLayer&amp;cx=c"></script>

<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXX-X&amp;l=dataLayer"></script>
```
I never specified the tag G-XXXXXXXXXX in any way in the configuration. Does vue-gtag add it's own tracking id?

**Comment by MatteoGabriele** [comment]
No, your application has probably already a tracker added.
