### ISSUE TITLE
how to use the $gtag method

### ISSUE THREAD

**Issue by pedro-olivenca** [MatteoGabriele/vue-gtag#388]
Hi there Matteo,

Thank you so much for this module.
I've manage to make it work with vue3 cli, but when trying to use the $gtag method, to register an event, I get an error

----
Property '$gtag' does not exist on type 'CreateComponentPublicInstance...
---

How can I make $gtag available on the components?

Thank you

**Comment by MatteoGabriele** [comment]
Could you show me what you have written? You are giving a lot to the imagination. 
Paste your installation and how you are using the code that creates this error.
Thanks
