### ISSUE TITLE
Proper way to use multiple tracker id in single site.

### ISSUE THREAD

**Issue by milez770** [MatteoGabriele/vue-gtag#392]
### Description

There aren't any documentation of using multiple tracker in one single site.

### Expected behavior

```
import Vue from 'vue'
import VueGtag from 'vue-gtag'

Vue.use(VueGtag, {
    config: { id: 'G-firstID' }
})
Vue.use(VueGtag, {
    config: { id: 'G-secondID' }
})
```

connects to multiple ids

### Actual behavior

It seems like it actually works, and that is great for me.
But nothing was specifically written on the document and wanted to check if this is the right way.

### Environment

implemented on Nuxt 2.15.8

**Comment by MatteoGabriele** [comment]
you can find it in the documentation https://matteo-gabriele.gitbook.io/vue-gtag/multiple-domain-tracking
```js
import Vue from "vue";
import VueGtag from "vue-gtag";

Vue.use(VueGtag, {
  config: { id: "UA-1234567-1" },
  includes: [
    { id: 'UA-1234567-2' },
    { 
      id: 'UA-1234567-3',
      params: {
        send_page_view: false
      }
    }
  ]
});
```

**Comment by panvakalo** [comment]
does this mean that we can put the Universal Analytics in `config` and then GTM and GA4 in separate items under `includes`?
