### ISSUE TITLE
Can I use without vue-router?

### ISSUE THREAD

**Issue by petegriffith** [MatteoGabriele/vue-gtag#394]
I'm using gtag for a small SPA without Vue Router, but when I `NPM run build` I get this error:

```
node_modules/vue-gtag/vue-gtag.d.ts:3:31 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.

3   import type { Router } from "vue-router";
```

Seems like this is just a types issue, but it's an annoying one. Do I have to have vue-router types to use this package?

**Comment by petegriffith** [comment]
After digging around a bit, I'm not sure if this package is usable without vue-router (assuming typescript). Happy to be told otherwise, I don't want to bloat my project without need!

**Comment by guyzyl** [comment]
@petegriffith I'm using it without `vue-router` and it's working as expected.

**Comment by petegriffith** [comment]
Are you using typescript? The inbuilt types import types from vue-router...

**Comment by guyzyl** [comment]
Yes, using typescript.
I now checked, I have `vue-router` installed to the project but I'm not using it, I guess that's the reason for it working.

**Comment by MatteoGabriele** [comment]
It would be helpful if you guys used the template I put on issues when you create one. There are multiple versions of this package with different versions of Vue, and they are very different.
Could you please be more mindful of this? 
What version are we talking about?
