### ISSUE TITLE
V 1.0 Release Date?

### ISSUE THREAD

**Issue by HMilbradt** [MatteoGabriele/vue-gtag#4]
Hey Matteo,

The company I work for is using vue-analytics and loving it, but we're wanting to migrate over to gtag for some of the newer features.

Do you have a status update on this library?  We'd love to hear about any plans for the release of this project, or about any of the roadblocks that are still holding it back.

Thanks

**Comment by MatteoGabriele** [comment]
Thanks for the feedback, unfortunately I'm struggling finding the time, but I'm working on it ( finding the time ). I'll have a look at the API again and see what's what.

**Comment by HMilbradt** [comment]
Thanks for your reply, I really appreciate it.  We'll likely continue using `vue-analytics` since there's no gtag library that's ready yet, but definitely update us if you're thinking you'll be able to complete it or not 🙏

**Comment by MatteoGabriele** [comment]
For sure! Luckily they didn't kill the analytics script yet so I have some time

**Comment by MatteoGabriele** [comment]
as you can see I started doing something 👍 
https://github.com/MatteoGabriele/vue-gtag/tree/develop/src

**Comment by MatteoGabriele** [comment]
@HMilbradt no release 1 maybe, but I have just release version 0.1.0 which is basically a safe version 1
didn't make any tests yet, nor finished documentation or add all features vue-analytics might have.

let me know if you tried

**Comment by MatteoGabriele** [comment]
this is what I need to do to go to v1 https://github.com/MatteoGabriele/vue-gtag/milestone/1
I hope I'll have time soon

**Comment by HMilbradt** [comment]
This is great, thank you so much for starting this 🙏.  I'll try to take a look at it this weekend to give some feedback on it.

**Comment by MatteoGabriele** [comment]
Perfect! Looking forward to it. I started doing some unit testing in the meantime

**Comment by MatteoGabriele** [comment]
well version 1 is out in the wild! 
let me know :)

**Comment by HMilbradt** [comment]
Thank you!  We will be checking this out soon and will definitely have feedback 🙏
