### ISSUE TITLE
npm install vue-gtag@next fails

### ISSUE THREAD

**Issue by TheDutchCoder** [MatteoGabriele/vue-gtag#411]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description
`npm install vue-gtag@next` does not install:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for vue-gtag@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/reinierkaper/.npm/_logs/2022-02-17T14_13_40_187Z-debug.log
```

### Expected behavior

The package to install.

### Actual behavior

The package does not install.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-gtag`: empty

Then, specify:

1. Operating system: MacOS 12.1
2. Browser and version: N/A

**Comment by Heromyth** [comment]
`npm install vue-gtag` works.

**Comment by UnKnoWn-Consortium** [comment]
It seems the author updated the tags at npm without updating the doc. 
Version 1.16.1 is now the ```legacy``` while version 2.0.1 is now the ```latest```. 

https://www.npmjs.com/package/vue-gtag

**Comment by MatteoGabriele** [comment]
Yes, since the official release of vue 3, this package default is version 2 (vue3 only), and legacy is version 1 (vue2 only), so there's no more next flag. I'm pretty sure documentation has been updated, but I have missed it; please point that out, and I will make sure to fix it.
thanks
