### ISSUE TITLE
Analytics does not recognize the change of view. 

### ISSUE THREAD

**Issue by c-peiron** [MatteoGabriele/vue-gtag#422]
I have installed everything correctly. I pass the vue-router instance to the .use but I only get in Analytics the first page loaded. 
Once I start browsing nothing more is sent.

**Comment by MatteoGabriele** [comment]
Please feel in the template if you think you have a bug, so I have more idea of your situation. This is too generic: I don't know which version of vue or vue-gtag, and I don't know your installation code.
