### ISSUE TITLE
How to use in Vue2/Vue3/Nuxt2/Nuxt3 with Partytown?

### ISSUE THREAD

**Issue by itsmnthn** [MatteoGabriele/vue-gtag#423]
Using [partytown](https://github.com/BuilderIO/partytown) is a great way to load analytics script using Web Worker to improve the initial app load.

I have been using the `vue-gtag` in my projects it is a great lib and I think having partytown support/integration will be cherry on top.

**Comment by itsmnthn** [comment]
I have working demo with `Nuxt2` but it doesn't support router and custom events. 

[nuxt2-partytown](https://github.com/itsmnthn/nuxt2-partytown)

there is also plugin for `Nuxt3` and `Nuxt2 with Nuxt-Bridge` : `@nuxtjs/partytown` [doc](https://partytown.builder.io/nuxt)

**Comment by MatteoGabriele** [comment]
Hi @itsmnthn 
Thanks for the suggestion; I don't think I've heard of partytown before. I will give you a look around and let you know. Do you know what support is needed to make the package work?
I currently get a "github.com is currently unable to handle this request." when I try to go and read the js/gtag.js file. Not sure what's the issue. I might try later on

**Comment by MatteoGabriele** [comment]
going to close it for inactivity

**Comment by itsmnthn** [comment]
Check this website [partytown.builder.io](https://partytown.builder.io/)

**Comment by itsmnthn** [comment]
#518
