### ISSUE TITLE
Implementing vue-gtag in Vue2 stops blob downloads?

### ISSUE THREAD

**Issue by tsposato** [MatteoGabriele/vue-gtag#429]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

When we implement vue-gtag, it breaks out existing file download functionality and I have no idea why.
Implementation is done via the standard way:
```
Vue.use(VueGtag, {
  config: {
    id: ['G-XXXXXXX']
  }
})
```

### Expected behavior

Files should download normally and analytics data being sent to Google.

### Actual behavior

Analytics data working but any file download functionality (where we convert base64 from backend to file download on out SPA frontend, comes as plaintext data instead of a file download.

### Environment

vue-gtag@1.16.1  

1. Occurs on Windows and Linux
2. Occurs on all Browsers

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by Stijn98s** [comment]
I also had the same problem with version 2.0.1. I fixed it by adding target _blank to the download element.

**Comment by MatteoGabriele** [comment]
I'm not sure how this package can compromise file downloading, but please create a reproducible demo outside your application.

**Comment by MatteoGabriele** [comment]
closing this one for inactivity
