### ISSUE TITLE
Exposing AdWords AccountId in the .JS file?

### ISSUE THREAD

**Issue by christoph-werker** [MatteoGabriele/vue-gtag#432]
Hello Together,

I just noticed that the plugin exposes the Ad-Words account in the source code. Is it possible to prevent this somehow? I use Webpack and include VueGtag as follows.

```js
Vue.use(VueGtag, {
    config: {id: "AW-xxxxxxxxx"}
});
```

See:
![image](https://user-images.githubusercontent.com/9929788/165391456-d536452e-b87e-4b78-92e4-c696364047ce.png)

I'm using the following Settings in Webpack:
```js
mix.options({
    cssNano: {
        discardComments: {
            removeAll: true,
        },
    },
    uglify: true,
    autoprefixer: true,

})
.polyfill({
        enabled: true,
        useBuiltIns: "usage",
        targets: "> 0.25%, not dead"
    })
.js('resources/js/backend/app.js', 'public/js/app.js').vue({extractStyles: false, globalStyles: false,})

```

Thanks for your help.

**Comment by MatteoGabriele** [comment]
The plugin doesn't expose anything: that's your bundle. In javascript, everything is exposed.
