### ISSUE TITLE
Users number is wrong in GA

### ISSUE THREAD

**Issue by v3nt** [MatteoGabriele/vue-gtag#443]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

Ony page views being recorded but Google Analytics is only ever seeing 1 users when there are hundreds

### Expected behavior

There should be more than 1 user  'in last 30 minutes'

### Actual behavior

Only 1 users is ever recorded

<img width="529" alt="Screenshot 2022-05-10 at 12 16 39" src="https://user-images.githubusercontent.com/6348562/167617178-f7f77c22-a0fa-4408-b024-c343395cca9c.png">

### Environment

vue-gtag@1.16.1 
nuxt@2.15.8 

1. Operating system: Mac OS
2. Browser and version: All / any

### Reproducible Demo
Code used for calling page view

      function recordPageview(name) {
        pageview(name);
      }
  
      watch(() => route.value.name, recordPageview);

Nuxt config

  ```
plugins: [
    { src: '~/plugins/gtag.client.ts' },
  ],
```

More stats the might be useful:

<img width="318" alt="Screenshot 2022-05-10 at 12 22 15" src="https://user-images.githubusercontent.com/6348562/167617539-f467ada3-9159-4cb5-942b-aeb210210ad4.png">

**Comment by MatteoGabriele** [comment]
Which version of vue are you using? The example you gave me seems made with vue 3, but you are using vue-gtag legacy for vue 2. I'm a bit confused

**Comment by MatteoGabriele** [comment]
closing this one for now activity
