### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by rnicholus** [MatteoGabriele/vue-gtag#45]
Thanks so much for creating this library, and its predecessor vue-analytics.

Do you have any plans to provide type definitions for vue-gtag? If not, and you're looking for someone to contribute this, would you prefer it to be maintained on DefinitelyTyped, or in this repo?

**Comment by MatteoGabriele** [comment]
I'm not sure. I've never worked with typescript tbh and on vue-analytics a contributor started working on it but I can't really judge the work has been done cause yeah...not a ts user 
is it normally hosted on DefinitelyTyped?

thanks a lot

**Comment by rnicholus** [comment]
It is preferable to host the definitions in the actual project. DefinitelyTyped is where these definitions are generally hosted if the target project cannot or will not host these definitions internally. I see your other project has a d.ts file, which indicates the type definitions are part of the project. Perhaps that is the best choice for vue-gtag.

**Comment by MatteoGabriele** [comment]
then yes, I think I'll have it in the repository.
I will try to work at it, checking also the work done in vue-analytics 

thanks for your feedback

**Comment by rnicholus** [comment]
If you're already going to take this on, I'm happy to review the types, if you'd like. I'm already building a limited set of type defs for a project i've pulled vue-gtag into (just covering the areas of the library i'm using).

**Comment by MatteoGabriele** [comment]
oh great! feel free to even make a PR if you feel like to.
thanks a lot
I'm currently moving apartments so gonna do a bit of Ikea and a bit of Open Source when i can ahahhahaha

cheers!

**Comment by romansp** [comment]
Hey, I'm late to the party. If only vue-gtag was written in typescript itself 💭 :eyes:. Anyway, I will be happy to contribute or review types as well.

**Comment by MatteoGabriele** [comment]
Ahahhahaha I never tried to use typescript, maybe one of these days I'll check it out, but you're definitely very welcome to contribute

Thanks as always

**Comment by GerryWilko** [comment]
I've created a pull request to add an intial typings file!

**Comment by MatteoGabriele** [comment]
forgot to add the close message in the commit, will do it manually :)
thanks again everyone for the PR
