### ISSUE TITLE
VueGtag doesn't work because of session cookies failure

### ISSUE THREAD

**Issue by ohadBrunner** [MatteoGabriele/vue-gtag#453]
I'm using VueGtag for sending events to Google Analytics. This is what my code looks like:

[Here I initiate the vuegtag and give it the right ID](https://i.stack.imgur.com/RpmN6.png)

[Here I use gtag.event to fire events to Google Analytics](https://i.stack.imgur.com/q2ET3.png)

I've got 2 data streams (different URL's), in one of them everything works smoothly and all the events are being sent to GA. In the other one, there is something wrong with the cookies which I can't wrap my head around. It seems like it can't initiate a new cookie session.

[This is what I get in the console every time an event is supposed to happen](https://i.stack.imgur.com/qKWyq.png)

**Comment by MatteoGabriele** [comment]
I don't know what this is about. Sorry 🤷 
It's a bit too generic of an issue for me to understand: there's no Vue version, no vue-gtag version, type of browser, is this a private browser? and so on.
not sure how to help you
