### ISSUE TITLE
Enhanced Conversion

### ISSUE THREAD

**Issue by christoph-werker** [MatteoGabriele/vue-gtag#464]
Hello Everyone,

i struggle to implement the enhanced conversion. I'm running on V1 from  `vue-gtag`  and need to implement the following code:

```
<script>
gtag('set', 'user_data', {
"email": yourEmailVariable, 
});
</script>
```

But this should be not possible 
https://github.com/MatteoGabriele/vue-gtag/blob/8c2e39555fb867a38251ca48c6011256603df69d/vue-gtag.d.ts#L228
![image](https://user-images.githubusercontent.com/9929788/181549550-128619a4-4dc0-4ff3-9161-8debe3a9b23a.png)

Looking forward to hearing from you.

**Comment by pcraston** [comment]
I'm also having problems with this.

Tried:

```
this.$gtag.set({
  user_data: { <email> },
})
```

but google ads is saying `Not enough matches for your conversions`

Anyone succeeded setting up enhanced conversions?

**Comment by christoph-werker** [comment]
@pcraston My Solution is the enhanced tracking with googletagmanager and the value as conversion variable.
```js
this.$gtag.event('conversion', {
  'value': "VALUE,
  "email": "EMAIL",
  });
```

**Comment by pcraston** [comment]
hi @christoph-werker 

thanks very much for replying. what do you mean by `enhanced tracking with googletagmanager`? did you set up googletagmanager in addition to vue-gtag or are you simply passing the email param as an additional argument to the conversion event of vue-gtag?

thanks for you help!

**Comment by christoph-werker** [comment]
Hi @pcraston,

you can see more information about the [enhance conv tracking](https://support.google.com/google-ads/answer/9888656?hl=en-GB) here. What you must do to get enhanced conversion tracking along with `vue-gtag` working is…
1. Include `email` in your `gtag.event` on your homepage
```js
this.$gtag.event('conversion', {
  'value': "VALUE,
  "VARIABLE_NAME": "EMAIL",
  });
```
2. Setup Google Tag Manager and create a variable in google tag manager in which you grab the information from the fired event. To get the data, you can access the email with `eventModel.VARIABLE_NAME`. Now you can do whatever you want with it. For example submit the email to enh. conversio ntracking.

Hope this helps
