### ISSUE TITLE
api documentation

### ISSUE THREAD

**Issue by andrewharvey** [MatteoGabriele/vue-gtag#50]
I just gave a sad face to "Was this page helpful" at https://matteo-gabriele.gitbook.io/vue-gtag/methods/events and wanted to provide feedback why.

I was expecting this to have the full API documentation for the method, ie. what exact parameters can I pass.

Coming from native gtag the method is `gtag('event', 'action', { 'event_category', category, 'event_label', label, 'value', value })` how to do this with $gtag is unclear.

**Comment by MatteoGabriele** [comment]
I get it's I'll try to improve the examples, but it's literally your event data left: the library provides the boilerplate so u technically pass only the data.

I will write some more snippets

**Comment by andrewharvey** [comment]
Yeah I just worked this out a second ago checking the source https://github.com/MatteoGabriele/vue-gtag/blob/master/src/api/event.js. Thanks.

**Comment by MatteoGabriele** [comment]
You basically only pass this part `'action', { 'event_category', category, 'event_label', label, 'value', value }`

**Comment by MatteoGabriele** [comment]
added some more clearance on the event structure and some links to the method in the official documentation. hope it helps

will for sure improve more along the way
