### ISSUE TITLE
How to include/use ecommerce?

### ISSUE THREAD

**Issue by DavydeVries** [MatteoGabriele/vue-gtag#53]
I like to use vue-gtag in combination of the [ecommerce](https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce) plugin of google. Any idea how to load/include `ga('require', 'ecommerce');`

Events can still be the same I guess? Example ecommerce event:
```
ga('ecommerce:addTransaction', {
  'id': '1234',                     // Transaction ID. Required.
  'affiliation': 'Acme Clothing',   // Affiliation or store name.
  'revenue': '11.99',               // Grand Total.
  'shipping': '5',                  // Shipping.
  'tax': '1.29'                     // Tax.
});
```

**Comment by MatteoGabriele** [comment]
yes in gtag they have changed the library a bit and also the name itself

**Comment by alexche77** [comment]
Hi @DavydeVries did you manage to track events related to ecommerce?
Here is some snippet of my setup maybe you can guide me.

I have many of this scattered over the code, I will give it some time for the data to arrive, but if you see something wrong, please let me know.

Thanks in advance!

![image](https://user-images.githubusercontent.com/8463460/92430754-eaf8af00-f152-11ea-8a80-b8d9ee23e3aa.png)

**Comment by MatteoGabriele** [comment]
@alexche77 you probably want to use the [purchase](https://matteo-gabriele.gitbook.io/vue-gtag/methods/purchase) method
