### ISSUE TITLE
Something happened and gtag.js couldn't be loaded

### ISSUE THREAD

**Issue by yooouuri** [MatteoGabriele/vue-gtag#54]
### Description

"gtag.js couldn't be loaded"

![image](https://user-images.githubusercontent.com/12934957/72715705-426cef00-3b71-11ea-800c-694e243b270b.png)

### Expected behavior

Is should load the gtag.js library.

### Actual behavior

"gtag.js couldn't be loaded"

### Environment

Using vue-gtag version 1.1.2.

1. Operating system: Mac OS 10.15.2 (19C57)
2. Browser and version: Google Chrome 79.0.3945.130

### Reproducible Demo

Created empty vue project with `vue create`, added vue-gtag by using `yarn add vue-gtag`

main.ts
```
Vue.use(VueGtag, {
  config: { id: 'GTM-XXXXXX' },
});
```

**Comment by MatteoGabriele** [comment]
you are most likely using a browser with ad blockers or an extension to block ads.

**Comment by yooouuri** [comment]
![image](https://user-images.githubusercontent.com/12934957/72716034-d76fe800-3b71-11ea-87e3-c6ef286bc870.png)

Do not have any adblockers...

**Comment by yooouuri** [comment]
@MatteoGabriele private window (Chrome and Safari) same error...

I am using a https://tagmanager.google.com/ account, is it possible to use it?

**Comment by MatteoGabriele** [comment]
now that I see your http request, I think you are passing the wrong ID. you use Google Analytics, Google Ads, and Google Marketing Platform.

**Comment by yooouuri** [comment]
Ah I need to use the https://tagmanager.google.com/ account.

Thanks for helping and sorry for you time.

**Comment by MatteoGabriele** [comment]
@yooouuri no worries! cheers

**Comment by ryexley** [comment]
So what was the solution here? Does this lib not work with `GTM-XXXXXXX` accounts? @yooouuri did you have to use something other than `vue-gtag`?

**Comment by MatteoGabriele** [comment]
@ryexley I don't think that was made to accept GTM ids

**Comment by ryexley** [comment]
I was actually able to get it to load. My issue, having encountered the same error, was that I had not "published" the tag manager workspace related to the GTM ID that I was using. Once I published it, it started loading fine.

**Comment by MatteoGabriele** [comment]
ah! good to know :)

**Comment by all-i-do-is-wynn2** [comment]
@ryexley - did you have to make any changes to the code? Our container is published and I am getting this error.
![image](https://user-images.githubusercontent.com/39102249/82457956-b6fe5e80-9a7b-11ea-8180-f396155fedb9.png)

**Comment by ryexley** [comment]
@all-i-do-is-wynn2 yes and no. We ultimately ended up moving away from using vue-gtag and just went with a custom implementation as we didn't really need the full integration with Vue. I'm sure that doesn't help you much though, sorry.

**Comment by all-i-do-is-wynn2** [comment]
@ryexley - thank you for the insight and the quick response!

**Comment by all-i-do-is-wynn2** [comment]
@MatteoGabriele - GTM ID does work. As a data analyst, if you have the "Preview" panel open at the bottom of the screen, it will throw the error in the console. Tell others to make sure that they close the Preview panel.

**Comment by MatteoGabriele** [comment]
Thanks a lot! Your comment here will help other people struggling with this one

**Comment by tv-munchkinlabs** [comment]
@MatteoGabriele Hello, my Google Optimize and GTag are both blocked by ad blocker. I do see you mentioned ad blocker, is there anyway to work around ad blockers?

**Comment by MatteoGabriele** [comment]
> @MatteoGabriele Hello, my Google Optimize and GTag are both blocked by ad blocker. I do see you mentioned ad blocker, is there anyway to work around ad blockers? 

I hope not 🤣
