### ISSUE TITLE
Reading cookie in cross-site context will be blocked in future Chrome versions

### ISSUE THREAD

**Issue by andyi95** [MatteoGabriele/vue-gtag#541]
### Description
New cookie cross-site warning in latest Chrome versions (currently 120.0.6099.111). The reference documentation https://developers.google.com/privacy-sandbox/3pcd#prepare_for_the_third-party_cookie_phase_out

![Screenshot_31](https://github.com/MatteoGabriele/vue-gtag/assets/25561815/05dd3978-abab-4632-b287-1e0742cb2a52)

### Environment 
Both pre-built bundle and development run using Vite.

NPM versions:

```
vue-gtag@2.0.1

+-- @vitejs/plugin-vue@4.5.2
| `-- vue@3.2.33 deduped
+-- naive-ui@2.35.0
| +-- @css-render/vue3-ssr@0.15.12
| +-- vdirs@0.1.8
| | `-- vue@3.2.33 deduped
| +-- vooks@0.2.12
| +-- vue@3.2.33 deduped
| `-- vueuc@0.4.51
|   `-- vue@3.2.33 deduped
+-- vue-gtag@2.0.1
| `-- vue@3.2.33 deduped
+-- vue-i18n@9.2.2
| `-- vue@3.2.33 deduped
+-- vue-router@4.0.14
| `-- vue@3.2.33 deduped
+-- vue@3.2.33
| `-- @vue/server-renderer@3.2.33
|   `-- vue@3.2.33 deduped
+-- vue3-clipboard@1.0.0
| `-- vue@3.2.33 deduped
`-- vuex@4.1.0
  `-- vue@3.2.33 deduped
```

### Reproducible Demo in case of a bug report

The live site with reproducible issue https://reader.dev.andyi95.com/

The plugin usage code in repo https://github.com/andyi95/reading-vue/blob/7cd56a8a5b816b3607fe070697d44b5066450b85/frontend/src/main.js#L19

**Comment by halfhp** [comment]
@andyi95 Looks like you're getting this from the `ar_debug` cookie, which in my case was indeed due to using the Google Tag Assistant.  Deleting the cookie got rid of that particular message:

https://support.google.com/analytics/thread/268576057/google-analytics-cookies-issue?hl=en

**Comment by andyi95** [comment]
You're absolutely right - checking on a "clean" Chrome instance didn't show any messages related to the cookies. Thanks a lot! 

![Screenshot_742](https://github.com/MatteoGabriele/vue-gtag/assets/25561815/3e0e7f95-41f1-451c-a2b3-f862d018bb0a)
