### ISSUE TITLE
Status of the project (where is Vue3 supported?)

### ISSUE THREAD

**Issue by euberdeveloper** [MatteoGabriele/vue-gtag#542]
Is this project still maintained?

I see some confusion, in the README it's written that it works with Vue3, but then it says to install "vue-gtag@next", that it appears not to exist.

In the documentation, it shows that it works for Vue 2 and to use "vue-gtag-next" for Vue 3, but it's 3 years it's not touched

**Comment by MatteoGabriele** [comment]
sorry for the delay!
- vue-analytics was a library for analytics.js
- vue-gtag was a vue2 library supporting gtag.js which is the successor of analytics.js
- vua-gtag-next was a temporary adjustment for vue3
- vue-gtag v2 is the current and latest version with vue3 compatibility and updates
confusing? maybe, but let's be honest, Google's product are also far for being super clear 😆

**Comment by vincerubinetti** [comment]
> Google's product are also far for being super clear 

This is very true and very fair. That said, your above comment was clarifying and could be helpful at the top of each readme. Archiving these repos as appropriate would also be helpful.
