### ISSUE TITLE
Tracking page views (dl, dh and dp query parameters)

### ISSUE THREAD

**Issue by fadeev** [MatteoGabriele/vue-gtag#55]
### Description

Hi! Thanks for `vue-analytics` and `vue-gtag`! I've noticed an unexpected behaviour when trying out `vue-gtag`.

### Expected behavior

Say we have two URLs: `example.org/about` and `example.org/contacts`. When I go from `/about` to `/contacts`, I expect `collect` request to have `dl=example.org/contact` or `dh=example.org&dp=/contact`.

### Actual behavior

What I see is `dl=example.org/about&dp=/contacts`. Is this intended behaviour? As far as I understand, there should be either only `dl` or both `dh` and `dp`, where `dl` is the location of the current document (`example.org/contacts`), `dh` is hostname and `dp` is the path.

https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dl

### Reproducible Demo

https://codesandbox.io/s/zen-gauss-9szcy

<img width="1143" alt="Screenshot 2020-01-20 at 18 05 17" src="https://user-images.githubusercontent.com/332151/72728550-75ce6e80-3baf-11ea-9afc-69f094e1dd0f.png">

If what I see is indeed unintended, maybe the problem is here:

https://github.com/MatteoGabriele/vue-gtag/blob/c8390791f0ffa0937b643cbb6df4df1fab62f8de/src/page-tracker.js#L31

`window.location.href` should be replaced with `window.location.host`

**Comment by MatteoGabriele** [comment]
@fadeev the documentation says that "page_location" is "The page's URL" and for me that's not the host but the entire URL.
not sure why it doesn't get the new one but the previous one, but it could be something with codesendbox maybe or some ssh issue if that's ssh based, I had this long issue on Nuxt with vue-analytics because the meta were not rendered yet and was registering the previous one

**Comment by fadeev** [comment]
Well, running the demo locally produces the same result, so it's not because of codesandbox.

<img width="1098" alt="Screenshot 2020-01-20 at 19 00 55" src="https://user-images.githubusercontent.com/332151/72732373-605d4280-3bb7-11ea-8092-1da4d8e0fa55.png">

I was wrong in the comment above. The line should read: `page_location: window.location.host + to.path`

Otherwise, `window.location.href` incorrectly returns the previous path (perhaps, it runs before the vue-router changes the URL). Anyways, just thought I'd mention it, because it seems like this is a bug.
