### ISSUE TITLE
Send events from Vuex

### ISSUE THREAD

**Issue by altescape** [MatteoGabriele/vue-gtag#56]
Hi @MatteoGabriele - firstly thank you for a fabulous plugin (also thank you for vue analytics)

This is just a quick query if I may.

Is it possible to send events or exceptions in my case from a Vuex module

I have a Vuex module in a file called auth.js and would like to send an exception to GA if an error happens in there, something along the lines of:

```
import { exception } from 'vue-gtag'

auth.checkSession((err, result) => {
  if (err) {
    exception({
      'description': err,
      'fatal': false
    })
  } else {
    // . . . carry on 
  }
})
```

I can't seem to get to work though am I doing something wrong or hasn't this been implemented (I haven't seen it in the docs so I'm guessing the latter) - if not implemented is there a way I can get to work?

**Comment by altescape** [comment]
A little bit more investigation and this works well for me:

```
import Vue from 'vue'

Vue.$gtag.event('event name', {
  'event_category': 'a-category',
  'event_label': 'a-label',
  'value': 21
})
```

**Comment by MatteoGabriele** [comment]
yeah I see, I actually forgot to export all events out. I might do it on this plugin too like vue-analytics

thanks for the feedback

**Comment by sirwalterious** [comment]
Thanks @altescape  - I came here to ask the same question.  :) 

Great plugin @MatteoGabriele!

**Comment by Jamie4224** [comment]
Just a quick comment, I think this should be added to the docs, I couldn't really find it quickly while a lot of people need this.
