### ISSUE TITLE
How should I integrate in nuxt3

### ISSUE THREAD

**Issue by luoriwusheng-xia** [MatteoGabriele/vue-gtag#567]
Please fill in at least the mandatory (*) questions below, or I will immediately close this issue without reading. Thanks

### Environment *

```
node: v20.12.2
"nuxt": "^3.11.2",
```

### Description *

Hope to have a basic case integrated in nuxt3

**Comment by luoriwusheng-xia** [comment]
Does the current plugin support nuxt3

**Comment by ernestchu** [comment]
https://nuxt.com/modules/gtag
FYI

**Comment by MatteoGabriele** [comment]
nuxt has already a module available as @ernestchu suggested
