### ISSUE TITLE
Update to GA4 Advanced Consent Mode

### ISSUE THREAD

**Issue by itspxly** [MatteoGabriele/vue-gtag#574]
Do you plan to update gtag to allow functionality of the GA4 Advanced Consent Mode. Seems like it is important to use it the new way, as described in https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced#tag-manager_3

Also, it will be helpful to manage gtag behaviour based on Consent Groups and Allow it to use cookieless signals when no consents are granted.

Hope it will help the project to evolve. Thanks!

**Comment by MatteoGabriele** [comment]
I won't be adding new features in the near future. This package works as a wrapper around gtag, so you can already use that with a few extra steps. If you'd like to contribute by creating a method that handles the advanced consent mode, feel free to make a pull request and I'll review it. 
Thanks for your time!
