### ISSUE TITLE
Boostrap later doesn't work

### ISSUE THREAD

**Issue by domisa54** [MatteoGabriele/vue-gtag#58]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

What are you reporting?
Boostrap later doesnt work

In main.js
import Vue from "./vue";
import store from "./FormStore.js";
import VueRouter from "vue-router";
import VueGtag from "vue-gtag";
Vue.use(VueGtag, {
    config: { id: "UA-xxxxxxxx-y" },
    router,
    bootstrap: false
});

In app.vue
import { setOptions, bootstrap } from 'vue-gtag';

  mounted() {
    bootstrap(gtag).then(() => {
        console.log("Gtag Actif ? ", gtag);
    });
}
>> get htis message in console

Vue warn]: Error in mounted hook: "ReferenceError: gtag is not defined"

found in

---> <App> at src\components\App.vue
       <Root>

### Expected behavior

Gtag should be defined
Tell us what you think should happen.

### Actual behavior
Vue warn]: Error in mounted hook: "ReferenceError: gtag is not defined"
Tell us what actually happens.

### Environment
Vue 2.0, windows 10 64 bits, Chrome browser ( idem with Mozilla)
Run this command in the project folder and fill in their results:

`npm ls vue-gtag`: 
`-- vue-gtag@1.2.0
Then, specify:

1. Operating system:
windows 10 64 bits,
2. Browser and version:
Chrome browser ( idem with Mozilla)
### Reproducible Demo
I folowed documentation :
import { bootstrap } from 'vue-gtag'

export default {
  name: 'MyComponent',

  methods: {
    enablePlugin () {
      bootstrap(gtag).then(() => {
        // all done!
      })
    }
  }
}
the bootstrap method will return a promise that will be resolved when the script has been loaded completely.
Please take the time to create a new app that reproduces the issue or at least some code example
In main.js
import Vue from "./vue";
import store from "./FormStore.js";
import VueRouter from "vue-router";
import VueGtag from "vue-gtag";
Vue.use(VueGtag, {
    config: { id: "UA-xxxxxxxx-y" },
    router,
    bootstrap: false
});

In app.vue
import { setOptions, bootstrap } from 'vue-gtag';

  mounted() {
    bootstrap(gtag).then(() => {
        console.log("Gtag Actif ? ", gtag);
    });
}
Demonstrable issues gets fixed faster.

Thank You in advance for your help

**Comment by MatteoGabriele** [comment]
try to remove the router instance from the plugin options, it needs to go in the third argument of the use method, not inside the options

**Comment by MatteoGabriele** [comment]
and also I just saw that you are taking the `gtag` instance from the bootstrap method, but it's inside the `then` because that's when the promise is resolved

**Comment by MatteoGabriele** [comment]
also quick tip, I left the instance there but you don't really need it, make sure that whenever you're using `this.$gtag` will be rendered or used after the bootstrap is completed so you don't have to pass gtag instances around your app

**Comment by domisa54** [comment]
Hi Matteo,

Than you very much for your fast reply and useful advices :-)
I removed the router instance but it was an example taken from your doc in Auto Tracking section.
I also passed the gtag in the 'then' clause but it was also based on your Doc in your Boostrap section
>>>I would suggest to update your doc ?
Anyway, now it works and both gtag and this.$gtag are boostrapped in app.vue.
**I have a last pb to fix.**
When I try to fire a GA event in a child component of Aap.vue linked to a specific route different from Root, like this  :
` this.$gtag('event', 'clic-calcul-devis', {'event_category' : 'lead','event_label' : 'page-index-devis'});`

 it appears that I get an error _TypeError: this.$gtag is not a function_ although this.$gtag was working in app..vue but the gtag instance is working... !?
>> do you have a hint about this and how to get this.$gtag working in that case ?

Thank you in advance
Dominique

**Comment by domisa54** [comment]
HI Matteo,
I resolved my last problem by looking more closely to your doc that appears to have been updated since 2 weeks ago. I realized that this.$gtag was an object {} and so I had to call this.$gtag.event() to send an event.
Now all is working perfectly > thank you very much for your great plugin 👍 !
Last question, if possible : do you know how to set up 'beacon' option like mentioned in gtag doc 
[https://developers.google.com/analytics/devguides/collection/gtagjs/sending-data]

> The following code sets the transport mechanism to 'beacon' for browsers that support it:

`gtag('config', 'GA_MEASUREMENT_ID', { 'transport_type': 'beacon'});`

Thank You very much,*

Dominique

**Comment by MatteoGabriele** [comment]
you can add it in your config object like so

```js
Vue.use(VueGtag, { 
  config: {
    id: 'GA_MEASUREMENT_ID',
    params: { 
      'transport_type': 'beacon'
    }
  }
})
```
