### ISSUE TITLE
Question: Custom Fields

### ISSUE THREAD

**Issue by tstrumfels** [MatteoGabriele/vue-gtag#59]
I had previously used your vue-analytics library, and I saw that you recommended vue-gtag going forward.  

We have a custom field for userId in our Google Analytics.  Below was the usage to tell vue-analytics about it.

In this case, looking to accomplish the same thing with vue-gtag - to pass in the userID field from my app into the vue-gtag library.

Thanks!

Vue.use(VueAnalytics, {
  id: "GAID",
  fields: {
      userId: "user123",
  },
  set: [

      { field: 'user_id', value: "user123" },

  ],
  router,

  debug: {
      enabled: false, // default value
      trace: false, // default value
      sendHitTask: true, // default value
  },
});

**Comment by MatteoGabriele** [comment]
you can achieve it by passing the params object in your configuration
```js
Vue.use(VueGtag, { 
  config: {
    id: 'GA_MEASUREMENT_ID',
    params: { 
      'user_id': 'user123'
    }
  }
})
```

https://matteo-gabriele.gitbook.io/vue-gtag/#initial-config-parameters

**Comment by tstrumfels** [comment]
Thanks Matteo! (good work on this, by the way!)

I will give this a go, although was able to achieve a different way as well.

Appreciate the timely response.

**Comment by sneko** [comment]
Hi @MatteoGabriele ,

Thanks for your answer. I'm wondering what would you recommend since the user can log in and log out.

I know there is the `setOptions()` I could use, but how to re-init the complete GTag flow?

Thank you,
