### ISSUE TITLE
Possible to wait until user consent is checked, and then track view?

### ISSUE THREAD

**Issue by newalphamedia** [MatteoGabriele/vue-gtag#76]
I have a script that runs on mounted() and checks with an axios response that the user has agreed to google analytics. This means that on each page load, an axios call is made which, if returned true (permission from user to use google analytics) we then call:

`launchGoogleAnalytics(){
        Vue.use(VueGtag, {
          config: { id: "my-id" },
          enabled: true
        });
      },`

Would this also track the current page view/session, or not? VueGtag is not loaded until after we confirm user consent, so I'm thinking maybe the page view won't be tracked?

**Comment by MatteoGabriele** [comment]
I would try to use this https://matteo-gabriele.gitbook.io/vue-gtag/custom-installation#bootstrap-later
this will bootstrap the plugin when and if the user agrees so it will also track the current page
