### ISSUE TITLE
v1.6.0 broke typescript support in strict mode

### ISSUE THREAD

**Issue by P4sca1** [MatteoGabriele/vue-gtag#80]
### Description
Trying to build a project that uses vue-gtag fails when type check and typescript strict mode is enabled.

### Expected behavior
Build should work in strict mode.

### Actual behavior
```
$ tsc --project ./tsconfig.json --noEmit
../../node_modules/vue-gtag/vue-gtag.d.ts:173:5 - error TS7010: 'config', which lacks return-type annotation, implicitly has an 'any' return type.

173     config(config?: GtagGenericParams);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/vue-gtag/vue-gtag.d.ts:174:5 - error TS7010: 'time', which lacks return-type annotation, implicitly has an 'any' return type.

174     time(timing: Timing);
        ~~~~~~~~~~~~~~~~~~~~~

../../node_modules/vue-gtag/vue-gtag.d.ts:208:30 - error TS7006: Parameter 'PluginOptions' implicitly has an 'any' type.

208   export function setOptions(PluginOptions): void;
```

### Environment
vue-gtag 1.6.0
MacOS Catalina
TypeScript 3.7.5

**Comment by MatteoGabriele** [comment]
@cesasol or @namoscato could you guys have a look at it? unfortunately I don't use typescript so I have no clue 🤣 
@P4sca1 you can also open a PR and fix it you know what's the issue.

thanks a lot!

**Comment by lisafrancoise** [comment]
In [vue-gtag.d.ts](https://github.com/MatteoGabriele/vue-gtag/blob/master/vue-gtag.d.ts) file, two functions doesn't have a return type and one parameter isn't typed which is causing the issue.

I had the same issue and have just updated this file

line 173
`config(config?: GtagGenericParams): any;`

line 174
`time(timing: Timing): any;`

line 208
`export function setOptions(PluginOptions: PluginOptions): void;`

That's not the best solution (especially for the "any" return type, it should be best to have the exact return type but I didn't dig deep into it) but it's a workaround for the moment.

**Comment by namoscato** [comment]
> could you guys have a look at it?

Yeah, I can take a pass within the next couple of days.

Looking at https://github.com/MatteoGabriele/vue-gtag/pull/63, some of the optional `event()` type properties were incorrectly reverted, so we'll have to fix that as well.
