### ISSUE TITLE
Opt-out for multiple domain tracking not working

### ISSUE THREAD

**Issue by lisafrancoise** [MatteoGabriele/vue-gtag#81]
### Description

Hello,
I'm trying to combine the use of multiple domain tracking, bootstrap and opt out but it doesn't seems to be working.

### Expected behavior

I would like for my user to be able to opt-in and opt-out simply by clicking on a button to activate it or not.

### Actual behavior

When I'm calling this.$gtag.optOut(), it stops triggering the main id (`UA-XXXXXXXX-1`) but the id specified in `includes` (`UA-XXXXXXXX-2`) is still used to trigger events to Google Analytics.

Here is my code in `main.ts`:

```
Vue.use(VueGtag, {
  config: { id: "UA-XXXXXXXX-1" },
  includes: [
    { id: "UA-XXXXXXXX-2" }
  ],
  bootstrap: false,
  enabled: false
}, router);
```

And when I'm using it:

```
bootstrap().then(() => {
  analyticalCookie.IsAccepted ? this.$gtag.optIn() : this.$gtag.optOut();
});
```

Maybe I misinterpreted something in the documentation and it works as supposed to.

Thanks in advance, I can give more details if needed :)

**Comment by MatteoGabriele** [comment]
you don't have to use the `enabled` at all, not even the optIn/optOut
since you are not bootstrapping, the plugin doesn't do anything unless you bootstrap it.
so basically just run the bootstrap function once the user is ok with it and everything should work

let me know

**Comment by lisafrancoise** [comment]
Hum, I think I didn't explain very well my use case, sorry!
(I will remove the `enabled: false` though)

A user comes to our website. There are two cases:

-  It's an anonymous user, so we opt-in by default, no problem for this case.
He can then log in and that leads us to the second case.

-  It's a logged user so we're checking if the user has accepted analytical cookies (by making a request to an external api). Depending on the result, we opt-in or opt-out. That was this code:
`analyticalCookie.IsAccepted ? this.$gtag.optIn() : this.$gtag.optOut();`
When the user is logged, he can navigate to a settings page where he can change if he wants to accept or not analytical cookies. So if he refuses, we call `this.$gtag.optOut()` and if he accepts, we call `this.$gtag.optIn()`.
And that's where we are having an issue. The `optOut()` doesn't work for our alternate domain tracking id.

Is it clearer this way?

**Comment by MatteoGabriele** [comment]
did you try to bootstrap it only when you have the permission?

**Comment by lisafrancoise** [comment]
That's already what I'm doing but the permission can change during the user navigation.

My issue is this one:

- A user logs to our website. We make an api call to know if they accepted analytical cookies. When we get the response, we bootstrap.
That user goes to the Settings page and decide that they don't want to accept analytical cookies anymore. So they click on a button and when they click, we are calling `this.$gtag.optOut()` to stop sending events to Google Analytics. It works for our main id (`UA-XXXXXXXX-1` in the first post) but not for the one added in the `includes` section (`UA-XXXXXXXX-2`). For this one, views events are still send to Google Analytics.

**Comment by MatteoGabriele** [comment]
aaaah ok I'm sorry I didn't get the last part. indeed I only applied it on the main config id

```js
import { getOptions } from "../install";

export default (value = true) => {
  const { config } = getOptions();
  window[`ga-disable-${config.id}`] = value;
};
```

I will fix it asap!

thanks a lot for your feedback

**Comment by lisafrancoise** [comment]
Thanks for your quick answer! :)
