### ISSUE TITLE
Checking if gtag has been initialized

### ISSUE THREAD

**Issue by jfanals** [MatteoGabriele/vue-gtag#83]
I am using bootstrap to set gtag after receiving the GA tracking id via an API.

There are times where there is no GA tracking id, so the gtag does not get initialized.

I would like to check if gtag has been configured before calling a tracking method (otherwise I get an error).

I have been trying to load the getOptions() method, but haven't been able to make it work.

What would be the best way to check if gtag has been initialized?

**Comment by MatteoGabriele** [comment]
right now you can use the `disableScriptLoad` but i am expecting an ID either way because you will need it after to start tracking

```js
Vue.use(VueGtag, {
  disableScriptLoad: true,
  config: {
    id: 'UA-1234567-8'
  }
})
```
