### ISSUE TITLE
anonymize-ip: true, how does it work?

### ISSUE THREAD

**Issue by JMeyer126** [MatteoGabriele/vue-gtag#86]
I am trying to send my requests to GA with 'anonymize_ip: true' but i can´t make it. I tried it within the options object and outside the options, with quotation marks and without...

I checked the Dev-Console networks tab for the 'collect?v...' request and would expected the "aip: 1' parameter in the query string parameters... 

What am i doing wrong?

my code:

import Vue from "vue";
import VueGtag from "vue-gtag";
import router from "./../router";

Vue.use(
  VueGtag,
  { config: { id: "UA-example-0" }, bootstrap: false  },
  router
);

i activate GA after checking the cookie with the bootstrap function.

**Comment by MatteoGabriele** [comment]
hi @JMeyer126 
where is your `anonymize_ip` property tho?

this should be your setup
```js
Vue.use(VueGtag, {
  bootstrap: false,
  config: {
    id: 'UA-1234567-8',
    params: {
      anonymize_ip: true
    }
  }
}, router)
```

**Comment by JMeyer126** [comment]
Hi! this works, thank you! Now in the GA requests is the "aip: 1" parameter.

I didn´t know that there is a params object. Now that i know this, i see it in your documentation, too. 
I always tried in in the config layer directly, like: 
Vue.use(VueGtag, {
  bootstrap: false,
  config: {
    id: 'UA-1234567-8',
    anonymize_ip: true
  }
}, router)

Thank you for your fast answer!!

**Comment by MatteoGabriele** [comment]
Thanks for your feedback, I'll try to improve the documentation

**Comment by JMeyer126** [comment]
Your step-by-step documention is easy to understand and your package works great due to gdpr.

**Comment by MatteoGabriele** [comment]
Thanks a lot :)
