### ISSUE TITLE
use gtag inside onReady

### ISSUE THREAD

**Issue by derevandal** [MatteoGabriele/vue-gtag#90]
Hi, I need to set gtag adwords' config.
I'm using onReady option with global gtag:

```js
onReady() {
  if (typeof gtag === 'function') gtag('config', 'AW-796275892')
}
```

There's another way?

**Comment by MatteoGabriele** [comment]
hi @derevandal 
can't you just use the normal configuration? not sure what you're trying to achieve

**Comment by derevandal** [comment]
I need to setup analytics and adwords inside gtag.
Analytics ID starts with `UA` and AdWords with `AW`.

Both need config event.

![image](https://user-images.githubusercontent.com/1340508/75923316-91ca5e80-5e43-11ea-843a-c60e2f7955c3.png)

**Comment by MatteoGabriele** [comment]
do you have to add it once or for all of your calls?

**Comment by derevandal** [comment]
all times when script started

Em qui, 5 de mar de 2020 16:51, Matteo Gabriele <notifications@github.com>
escreveu:

**Comment by MatteoGabriele** [comment]
what about this

```js
Vue.use(VueGtag, {
  config: {
    id: 'UA-1234567-7'
  },
  includes: [
    { id: 'AW-12345678-7' }
  ]
})
```

https://matteo-gabriele.gitbook.io/vue-gtag/multiple-domain-tracking

**Comment by derevandal** [comment]
it works!
thanks a lot! <3
