### ISSUE TITLE
just test for issue

### ISSUE THREAD

**Issue by juel95** [MatteoGabriele/vue-gtag#99]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

What are you reporting?

### Expected behavior

Tell us what you think should happen.

### Actual behavior

Tell us what actually happens.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-gtag`: 

Then, specify:

1. Operating system:
2. Browser and version:

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by MatteoGabriele** [comment]
not sure if this is an error or you just have nothing better to do.
